NEWS.md
R/RcppExports.R
R/class-workbook.R
R/pugixml.R
man/xml_add_child.Rd
src/RcppExports.cpp
src/pugi.cpp
tests/testthat/test-pugi_cpp.R
tests/testthat/test-pugixml.R

Tested with:
```R
wb$add_worksheet("databar")
wb$add_data("databar", -5:5, startCol = 1)
wb_conditional_formatting(
wb,
"databar",
cols = 1,
rows = 1:11,
type = "databar"
) ## Default colours
wb$add_data("databar", -5:5, startCol = 3)
wb_conditional_formatting(
wb,
"databar",
cols = 3,
rows = 1:11,
type = "databar",
showValue = FALSE,
gradient = FALSE
) ## Default colours
wb$add_data("databar", -5:5, startCol = 5)
wb_conditional_formatting(
wb, 
"databar",
cols = 5,
rows = 1:11,
type = "databar",
style = c("#a6a6a6"),
showValue = FALSE
)
wb$add_data("databar", -5:5, startCol = 7)
wb_conditional_formatting(
wb,
"databar",
cols = 7,
rows = 1:11,
type = "databar",
style = c("red"),
showValue = TRUE,
gradient = FALSE
)
wb$add_data("databar", -5:5, …
```

[R/conditional_formatting] fix multiple databar entries per sheet

---

R/class-worksheet.R
R/wb_functions.R
R/wb_styles.R
src/helper_functions.cpp
src/load_workbook.cpp
src/openxlsx2_types.h
src/write_file.cpp
tests/testthat/test-clean_sheet.R
tests/testthat/test-writeData.R

[c++/empty cells] Empty cell information is now displayed with "" instead of "_openxlsx_NA_" as before. Previously this variable was used to help various `wbWorkbook` functions to distinguish between empty cells, missing cells and cells to be ignored. Fortunately, this is no longer needed. Either a cell contains useful information or it can be ignored. Empty strings are written as `<is><t></t></is>` or they are still sharedstrings. Row and column information cannot be empty, similarly openxml has no empty attributes (as far as I know).
This relieves us of the time-consuming burden of initializing each field of cc with the long string "_openxlsx_NA_" (it was intentionally that long to prevent someone from randomly selecting it in an xlsx file). However, since this string was used …

Empty cell information

---

R/wb_functions.R

This cuts the time wasted doing ... nothing. Oh this did cost me almost a day, tweaking back and forth 😄 (I hate optimizing my own code). Though I assume there are a few other places where we simply select something and try to get away with it. (Edit: With other places I mean functions I wrote and with we I mean me ofc 🙈 )
```R
Unit: milliseconds
expr       min        lq      mean    median        uq       max neval
wb_old <- openxlsx::loadWorkbook(xlsxFile) 119.04867 122.62752 129.43213 125.08641 128.56099 204.89869    25
wb_new <- openxlsx2::wb_load(xlsxFile)  82.15260  83.24123  86.36275  85.13675  86.59532  96.14397    25
x_old <- openxlsx::read.xlsx(wb_old, sheet = sheet)  11.82465  12.44604  17.24027  12.83931  13.56616  98.14137    25
x_new <- openxlsx2::read_xlsx(wb_new, sheet = …
```

Wb to df cleanup

---

NEWS.md
R/wb_load.R

Removes the printer setting and the reference in pageSetup. This fixes the following on my work laptop with Windows 10 and Excel 2016:
```R
wb_load(file = system.file("extdata", "loadExample.xlsx", package = "openxlsx2"))$open()
```
This is one of the ids, @jmbarbone, that I have always wanted to document:
The reference is in sheet2 (`xl/worksheets/sheet2.xml`) and matches a reference in `xl/worksheets/_rels/sheet2.xml.rels` that points to an external file: `xl/printerSettings/printerSettings1.bin`. The other references here are hyperlinks and a drawing. Even if we remove `r:Id="6"`, Excel does not complain because the other references are still valid. I haven't checked, but I suspect Excel would complain or, worse, abort altogether if we assigned `r:Id="6"` to something else without …

[R/load] remove references to printerSettings.bin. Closes #184

---

NEWS.md
R/wb_load.R
src/load_workbook.cpp
tests/testthat/test-read_sources.R

```R
wb_load(xlsx)$open()
```
There is some issue with sharedStrings. So far I'm unaware to locate the problem. Maybe something to do with the encoding? Sadly it was always in xlsx files with many many shared strings.

[c++/load] load file without row attribute

---

R/class-workbook.R
src/pugi.cpp
src/strings_xml.cpp
src/styles_xml.cpp
src/write_file.cpp
tests/testthat/test-pugixml.R

Previously pugi would reduce `<si><t xml:space="preserve"> </t>` to this `<si><t xml:space="preserve"/></si>`. This confused a certain spreadsheet software.

[c++/pugi] use parse_ws_pcdata. closes #188

---

NEWS.md
src/helper_functions.cpp
src/load_workbook.cpp
src/openxlsx2.h
tests/testthat/test-read_sources.R

fix reading example file with missing `r=` attribute. This file has a few columns with this attribute, but most do not have it. Previously we were simply counting the columns, this lead to duplicates which confused a certain spreadsheet software. Reading the example file is now fixed. Though this is a single known case of such a file, I would not state that it works for every case.

[R/load] fix duplicates in example file with missing r attributes

---

R/readWorkbook.R
R/wb_functions.R
R/wb_load.R
man/wb_load.Rd
tests/testthat/test-loading_workbook.R

This allows reading a striped down version of wbWorkbook with only sheet_data. Thought that this would speed read_xlsx a bit up, but could not measure any difference

provide data_only mode for wb_load()

---

NEWS.md
R/utils.R
R/wb_load.R
R/xl_open.R
man/temp_xlsx.Rd
tests/testthat/test-read_sources.R

skip names assignment for conditional formatting, this was broken too.

[R/load] guard against broken vml. closes #201 and #200

---

src/load_workbook.cpp
src/openxlsx2_types.h
src/styles_xml.cpp
tests/testthat/test-class-workbook.R
tests/testthat/test-styles_xml.R

We do not really benefit from these `Rcpp` functions. Therefore they should be replaced with native c++ or functions we benefit from. This could enable us to build with `#include <Rcpp/Lightest>`.

[c++] remove match from `col_to_df()`

---

.github/workflows/check-standard.yaml
openxlsx2.Rproj
src/helper_functions.cpp
tests/testthat/test-read_sources.R
tests/testthat/test-utils.R

Well, `R 4.2.1` was released today so maybe our `oldrel-1` will be valid again.
Couldn't figure out what was causing this to fail in `R 4.1.3`

re-enable oldrel-1

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/write.R
R/write_xlsx.R
man/update_cell.Rd
man/wbWorkbook.Rd
man/wb_add_data_table.Rd
man/write_data.Rd
man/write_data2.Rd
man/write_datatable.Rd
tests/testthat/test-save.R

Add option to write custom `na.strings`. It is `na.strings` even though it allows just a single value, to match the identical argument when reading. This allows three options if `na.strings`
* is missing: write `#N/A` exception to output
* is NULL: write nothing
* is character or numeric: write `inlineStr` of `as.character(na.strings)`
This applies to `NA` only and is intended to be used when replacing `NA` in numeric data with character strings or empty cells.

[R/write] add na.strings argument to write functions

---

R/class-sheet-data.R
R/class-workbook.R
R/class-worksheet.R
README.md
openxlsx2.Rproj

Initial update to print returns
* Only return useful output
* Wrap all `self` in `invisible(self)`. We have talked about this in #164 and #46, but there hasn't been much progress and all the noisy output is really ugly and not helpful at all
As discussed previously: in the future we might want to add something similar to the sheet waiver for output messages. Something like this:
* create Workbook. Output is `a workbook`
* add a worksheet foo. Output is `a workbook \n+ worksheet foo`
* add data bar to worksheet foo. Output is `a workbook \n+ worksheet foo \n+ data bar`
* etc

[R/print] update print returns

---

R/helperFunctions.R
tests/testthat/test-helper_functions.R

If the imported file has empty left/center/right header/footer values, the xml output contains only strings unequal to `""`:
```XML
<headerFooter differentOddEven="0" differentFirst="0" scaleWithDoc="0" alignWithMargins="0">
<oddHeader>&amp;C&amp;&quot;Times New Roman,Standard&quot;&amp;12&amp;A</oddHeader>
<oddFooter>&amp;C&amp;&quot;Times New Roman,Standard&quot;&amp;12Seite &amp;P</oddFooter>
</headerFooter>
```

[R/save] fix writing headerFooter. fixes #261

---

R/write.R
tests/testthat/test-save.R

This allows creating entirely empty canvas as shown in the added test.
```R
dat <- as.data.frame(matrix(NA, 2, 2))
add_data(x = dat, startRow = 2, startCol = 2, na.strings = NULL, colNames = FALSE)
wb$worksheets[[1]]$sheet_data$cc$c_t <- ""
wb$add_fill(dims = "B2:C3", color = c(rgb = "FFFFFF00"))
wb$add_border(dims = "B2:C3")
```

[R/save] fix writing integers without colNames

---

NEWS.md
R/write.R
src/RcppExports.cpp
src/helper_functions.cpp

Well, sometimes it's the little things, like writing correct c++-code.
```R
> library(microbenchmark)
> library(openxlsx2)
> 
> # a larger data frame with strings, missings and numbers
> xlsxFile <- system.file("extdata", "readTest.xlsx", package = "openxlsx2")
> wb1 <- wb_load(xlsxFile)
> data <- wb_to_df(wb1, sheet = 3, skipEmptyRows = TRUE)
> 
> res <- microbenchmark::microbenchmark(
+   wb <- wb_workbook()$add_worksheet()$add_data(x = data),
+   wb <- wb$add_data(x = data),
+   times = 25
+ ); res
Unit: milliseconds
expr       min        lq     mean    median        uq       max neval
wb <- wb_workbook()$add_worksheet()$add_data(x = data)  31.77736  32.08635  34.6002  32.37475  32.69734  44.95653    25
wb <- wb$add_data(x = data) 143.69455 145.38906 149.5828 146.44222 155.83526 …
```

[R/update_cell_loop] further speedups

---

R/wb_styles.R
tests/testthat/test-conditional_formatting.R

Disable colors in dxfs style:
```R
> create_dxfs_style(font_color = NULL, bgFill = NULL)
[1] "<dxf><font><name val=\"Calibri\"/><sz val=\"11\"/></font></dxf>"
```

Allow creation of dxfs style w/o font and bg color. closes #291

---

R/wb_styles.R
tests/testthat/test-conditional_formatting.R

Allows this:
```R
yel_style <- create_dxfs_style(font_name = NULL, font_size = NULL)
```

Dxf nofont

---

R/wb_styles.R
tests/testthat/test-wb_styles.R

When working with a loaded sheet, we tried to get the n+1 object from a vector of length n

fix get_cell_styles

---

NEWS.md
R/readWorkbook.R
R/wb_functions.R
R/write_xlsx.R
man/read_xlsx.Rd
man/wb_read.Rd
man/wb_to_df.Rd
tests/testthat/test-save.R

Write na.strings with `write_xlsx()` and read `na.strings()` and `na.numbers()`. 
```R
> df <- data.frame(
+   num = c(1, -99, 3, NA_real_),
+   char = c("hello", "99", "3", NA_character_)
+ )
> 
> test <- temp_xlsx()
> write_xlsx(df, file = test, na.strings = "N/A")
> 
> read_xlsx(test, na.strings = "N/A", na.numbers = -99)
num  char
2   1 hello
3  NA    99
4   3     3
5  NA  <NA>
```

improve NA handling #closes #300

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/class-worksheet.R
R/dates.R
man/get_date_origin.Rd
man/wbWorksheet.Rd
tests/testthat/test-class-workbook.R
tests/testthat/test-helper_functions.R

Certain data validation is an x14 extension. Previously, it was added to dataValdiationLst and moved to extLst when saving. When loading, it remained in extLst. This caused problems when a second dataValidationsLst entry was added. Now, dataValidationsLst is skipped completely. Instead, we write directly to extLst using the approach used with sparklines.

[R/dataValidation] Fixes #277.

---

NEWS.md
R/class-workbook.R
R/class-worksheet.R
R/utils.R
R/wb_load.R
tests/testthat/test-read_sources.R

Implement user defined chartShapes. Previously this was not implemented instead the previous logic assumed that every sheet has a matching drawing, whereas we can have these user defined chartShapes drawing files that are numerated just like every other sheet.
```R
fl <- "https://github.com/JanMarvin/openxlsx-data/raw/main/unemployment-nrw202208.xlsx"
wb_load(fl)$open()
```
This should be added with #311, otherwise we might end up with broken references, if we add workbooks after a chartShape that is unaware of the drawings issue.
Cloning is possible and adding images is possible too
```R
wb <- wb_load(fl)
img <- system.file("extdata", "einstein.jpg", package = "openxlsx2")
wb$add_image("Uebersicht_Quoten", img, startRow = 5, startCol = 3, width = 6, height = 5) …
```

Improve drawings

---

R/class-workbook-wrappers.R
R/class-workbook.R
R/openxlsx2.R
man/openxlsx2.Rd
man/wb_add_sparklines.Rd
tests/testthat/test-class-workbook-wrappers.R
tests/testthat/test-options.R

resolves #329 
- remove whitespace
- add sheet name to option list
- redoc

329 sheet name

---

R/class-worksheet.R
tests/testthat/test-class-worksheet.R

Allow differen uri for data validations and sparklines. My initial assumption was that the uri id does not matter, there are plenty of cases where we do not even provide uri ids (worksheet rels). With extLst this is not true. If we do not provide the correct uri id, Excel will not show a dropdown or sparkline.
This should be fixed now. The following works.
```R
s1 <- create_sparklines("Sheet 1", "A3:K3", "L3")
s2 <- create_sparklines("Sheet 1", "A4:K4", "L4")
add_worksheet()$add_data(x = iris[1:30,])$
add_worksheet()$add_data(sheet = 2, x = sample(iris$Sepal.Length, 10))$
add_data_validation(sheet = 1, col = 1, rows = 2:11, type = "list", value = '"option1,option2"')$
add_sparklines(sparklines = s1)$
add_data_validation(sheet = 1, col = 1, rows = …
```

enable multiple ext in extLst

---

R/baseXML.R
R/class-workbook-wrappers.R
R/class-workbook.R
R/class-worksheet.R
R/converters.R
R/write_xlsx.R
man/wbWorkbook.Rd
man/wb_modify_basefont.Rd
man/wb_set_col_widths.Rd
tests/testthat/test-base_font.R
tests/testthat/test-class-workbook.R
tests/testthat/test-wb_styles.R

This adjusts a few functions to use default column width of 10 and default font size 12. This is what MS365 uses on Mac. It is changed, because otherwise column widths were slightly off. 9. something instead of 10. Adjusted to this new values, all calculations are correct for Calibri. Yet, I would not bet that our calculations are valid for all versions. Previously we were using 8.43 and font size 11 as default. Which might be correct for the MS365 webbrowser edition or certain Windows low dpi versions.
Maybe you can check the following on Windows @jmbarbone ? On Mac the column width is exactly 8.5 ... 17.5.
```R
set_col_widths(cols = 1:10, width = (8:17) + .5)$
add_data(x = rbind(8:17), colNames = FALSE)$
open()
```

change default col size to 10

---

NEWS.md
R/baseXML.R
R/class-workbook.R
R/wb_load.R
tests/testthat/test-loading_workbook.R

* cleanup of baseXML
* fix opening workbooks with slicer
* fix cloning pivot charts
Unfortunately I didn't check loading sheets with and without slicers or I misinterpreted the errors I saw when cloning slicers. 
```R
wb <- wb_load(file = system.file("extdata", "loadExample.xlsx", package = "openxlsx2"))$
clone_worksheet(old = "irisSample", new = "clone 1")$
open()
```

[wb_load] xml cleanup

---

R/class-workbook.R
tests/testthat/test-wb_styles.R

This creates names as xml strings
```R
sheet <- mtcars[1:6, 1:6]
wb <- wb_workbook() %>%
wb_add_worksheet("test") %>%
wb_add_data(x = "Title", startCol = 1, startRow = 1) %>%
wb_add_font(dims = "A1", bold = "1", size = "14") %>%
wb_add_data(x = sheet, colNames = TRUE, startCol = 1, startRow = 2, removeCellStyle = TRUE) %>%
wb_add_cell_style(dims = "B2:F2", horizontal = "right") %>%
wb_add_font(dims = "A2:F2", bold = "1", size = "11") %>% 
wb_add_numfmt(dims = "B3:D8", numfmt = 2) %>% 
wb_add_font(dims = "B3:D8", italic = "1", size = "11") %>% 
wb_add_fill(dims = "B3:D8", color = wb_colour("orange")) %>% 
wb_add_fill(dims = "C5", color = wb_colour("black")) %>% 
wb_add_font(dims = "C5", color = wb_colour("white"))
wb %>% wb_open()
```

[styles] avoid sample names. fixes #383

---

NEWS.md
R/baseXML.R
R/wb_load.R
tests/testthat/test-loading_workbook.R

Avoid adding `sharedStrings.xml` to `workbook.xml.rels`. This is just a patch to solve issue #360. The better fix would be to not mess with `workbook.xml.rels` at all when loading. Though that requires a deeper look at the code. This is based on #362.

Gh issue 360

---

NEWS.md
R/write.R
man/write_data2.Rd
tests/testthat/test-write.R

Previously, when using `rownames = TRUE` when writing data, we would add a cell with `1` in top left box (the name for the rownames). This has been changed:
* when writing data: we do not fill this cell at all.
* when writing a data table: we fill this cell with `_rowNames_`.
_IIRC_ data tables require unique column names and can not be empty. 
```R
wb$add_worksheet()$add_data(x = mtcars, rowNames = TRUE)
wb$add_worksheet()$add_data_table(x = mtcars, rowNames = TRUE)
wb$open()
```

[add_data_table] improve rowNames. closes #354

---

NEWS.md
R/baseXML.R
R/class-workbook-wrappers.R
R/class-workbook.R
R/class-worksheet.R
R/converters.R
man/wbWorkbook.Rd
man/wb_modify_basefont.Rd
tests/testthat/test-base_font.R
tests/testthat/test-class-workbook.R
tests/testthat/test-wb_styles.R

I have updated to font size settings to default to column width of 8.43 and a font size of 11 and to use the windows size setting. On Mac the column width will be slightly off, but otherwise we'd have to skip a couple of tests.
~~This adjusts a few functions to use default column width of 10 and default font size 12. This is what MS365 uses on Mac. It is changed, because otherwise column widths were slightly off. 9. something instead of 10. Adjusted to this new values, all calculations are correct for Calibri. Yet, I would not bet that our calculations are valid for all versions. Previously we were using 8.43 and font size 11 as default. Which might be correct for the MS365 webbrowser edition or certain Windows low dpi versions.~~
Maybe you can check the following on Windows @jmbarbone ? …

[reland] cleanup column width and font size setting

---

NEWS.md
R/wb_load.R
tests/testthat/test-loading_workbook.R

We update vmlDrawing name, but ignored it in worksheets_rels.

[wb_load] update vml file name. fixes #402

---

NEWS.md
R/pugixml.R
R/wb_load.R
man/wb_load.Rd
tests/testthat/test-loading_workbook.R
tests/testthat/test-pugixml.R
tests/testthat/test-read_sources.R

allow reading files with x namespace
This fixes import for files created by third party software as seen in https://github.com/ycphs/openxlsx/issues/344.
Maybe one of you can test this @Matpli, @elinw? You can build this branch using:
```R
remotes::install_github("JanMarvin/openxlsx2", ref = "gh_issue_213")
```
I have taken the initial #213 and created a few more safeguards to make sure that we do not have to check every xml file we import. 
1. Instead now we only check if we find `x:workbook` in `/xl/workbook.xml` 
1. If TRUE set `options("openxlsx2.has_x_namespace" = TRUE)`
1. If this option is true we read the file into R
1. If this string is found `xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"`, we will remove the `x` namespace from the input
1. We let the user …

[wb_load] read x namespace

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
man/named_region.Rd
man/wbWorkbook.Rd
tests/testthat/test-helper_functions.R

Not all of them are user relevant. Comment and hidden seem to be the only working.
* write global and local named regions
* write comments for named region
* write hidden named regions
```R
wb <- wb_workbook()$add_worksheet()$add_data(x = iris)
wb$add_named_region(
sheet = 1,
name = "iris",
rows = seq_len(nrow(iris) + 1),
cols = seq_along(iris),
comment = "test"
)
wb$add_named_region(
sheet = 1,
name = "iris_head",
rows = 1,
cols = 1,
hidden = "1"
)
wb$add_worksheet()$add_data(x = iris)
wb$add_named_region(
sheet = 2,
name = "iris",
rows = seq_len(nrow(iris) + 1),
cols = seq_along(iris),
localSheet = TRUE
)
wb$add_formula(x = "'Sheet 1'!iris_head", dims = "H1")
wb$open()
```

add further named region arguments

---

NEWS.md
R/class-workbook.R
R/wb_load.R
man/wbWorkbook.Rd
tests/testthat/test-read_sources.R

Connections created with powerquery use a top level folder `customXml`. This was previously ignored.
@nicojx this might solve your issue with disappearing connections

handle customXml folder

---

NEWS.md
R/baseXML.R
R/class-workbook.R
R/wb_load.R
tests/testthat/test-loading_workbook.R

If a formula in a workbook originally created by Excel refers to a cell modified by `openxlsx2`, the formula was not recalculated when loaded in Excel. The formula was update only if the cell was visited and Enter was hit. This was hard to spot could easily result in errors. This was solved enforcing [`fullCalcOnLoad`](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.calculationproperties.fullcalculationonload?view=openxml-2.8.1).
This also brings `revisionPtr` simply to reduce visual differences when comparing two files.

Enforce `fullCalcOnLoad`. closes #427

---

NEWS.md
src/helper_functions.cpp
tests/testthat/test-save.R

Previously we escaped when writing to the workbook and when saving the workbook as file, we were escaping a second time.

[wb_add_data] fix double escapes. fixes #436x

---

R/wb_functions.R
tests/testthat/test-fill_merged_cells.R

Hi @JanMarvin,
i found a minor problem while reading merged cells. If the merged area only contains NA values the import fails with an error. I saw this error in combination with startRow (after selecting a different startRow the merged cells became all NA)
```
library(testthat)
wb$add_worksheet("sheet1")
wb$add_data(1, t(matrix(c(1:3, NA_real_), 4, 4)), startRow = 3, startCol = 1, colNames = FALSE)
wb$merge_cells(1, rows = 1:4, cols = 4)
tmp_file <- temp_xlsx()
wb_save(wb, tmp_file)
read_xlsx(tmp_file, fillMergedCells = FALSE)
read_xlsx(tmp_file, fillMergedCells = TRUE)
```
A simple solution is checking if the merged cells are all NA and skip this cell range. I created a pull request with a possible solution and a new test.

Fix fill merged cells

---

NEWS.md
R/class-workbook.R
R/utils.R
R/wb_load.R
man/wbWorkbook.Rd
tests/testthat/test-read_sources.R

Implement loading and writing of [form control](https://support.microsoft.com/en-us/office/add-a-check-box-or-option-button-form-controls-9f201e46-8f6b-4a9d-a320-f44b28088cb0).

implement formControl. closes #206

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/class-worksheet.R
R/utils.R
man/wbWorkbook.Rd
man/wbWorksheet.Rd
man/wb_grid_lines.Rd
tests/testthat/test-class-worksheet.R

Only visible change is seen when printing in spreadsheet software that supports openxml [`<printOptions/>`](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.printoptions?view=openxml-2.8.1).

improve print options. closes #393

---

NEWS.md
R/wb_load.R
man/wb_load.Rd
tests/testthat/test-loading_workbook.R
tests/testthat/test-read_sources.R

Previously I wanted to improve calculation chain modifications in #432, but they remain a nuisance. Therefore this PR adds a new argument `calc_chain` to `wb_load()` to entirely ignore loading the calculation chain, which will be the default.
Basically
* the sheet id in the calculation chain must not match our internal sheet id. Adding or removing sheets on our end might change the id. Therefore if the user overwrites a cell in the calculation chain, we might update the wrong calculation chain cell. Ergo: unless someone puts in some work to really improve this situation, our way of dealing with the file remains error prone and will leave the user with the usual useless Excel error message.
* The calculation chain is only partially supported in other spreadsheet software. LibreOffice …

add calc_chain argument to wb_load. closes #432 

---

.lintr
NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
man/wb_add_plot.Rd
vignettes/openxlsx2_charts_manual.Rmd

This includes changes in
* `wb_add_plot()` example and replaces the `qplot()` function with `ggplot()`
* changes `wb_add_image()` function to `add_drawing()` the previous did not work as expected in the example

Charts vignette

---

NEWS.md
R/pugixml.R
R/wb_functions.R
R/wb_load.R
tests/testthat/test-read_sources.R

This is https://github.com/ycphs/openxlsx/issues/394 (found it via https://asterhu.com/import-excel-formula-with-ampersand-to-r/)
Could you check if this solves your issue @aster-hu?

fix reading of xml escapes

---

R/class-workbook.R
tests/testthat/test-outlines.R

group above/below or left/right, depending on the worksheet outlinePr. Currently this only works with the current worksheet value to avoid strange grouping results and there is no internal function to set this.

Group depending on outlinePr

---

NEWS.md
R/class-workbook.R
tests/testthat/test-loading_workbook.R

Previously this would select sheet one per default in certain cases. Related to #399 . Similar to #505  fixing old code parts, that were never understood, but updated and fixed incorrectly.
```R
wb <- wb_load(file = system.file("extdata", "loadExample.xlsx", package = "openxlsx2"))
wb$get_sheet_names() # list worksheets
wb ## view object
```

fix tab selection

---

NEWS.md
R/RcppExports.R
R/openxlsx2.R
R/write.R
src/RcppExports.cpp
src/helper_functions.cpp
src/openxlsx2_types.h
tests/testthat/test-write.R

This PR provides a `string_nums` option for `openxlsx2` to control if strings that can be expressed as numerics should be written as styled numerics and not as character strings (e.g. `"1"` as `1`). ~~This does not provide on the fly conversions from strings to numerics (which ... would be possible as well; simply avoid writing the style to the cell).~~
This needs some testing (accuracy and speed) and for now I have hidden it with an option. This option knows states 0 (the current default), 1 (write string as number with cell style) and 2 (write string as number). The entire conversion part likely will have an impact on writing time, due to the call to `is_double()`.
``` r
dat <- data.frame(x = "2023", y = 2023)
options("openxlsx2.string_nums" = 1) …
```

[wb_add_data] string_nums option. closes #503

---

src/helper_functions.cpp

This makes use of the pointer element of `Rcpp:Characters`. Since they are pointers to memory, we can extract them from the `Rcpp::DataFrame` and modify them _and_ the modification will be present in the `Rcpp::DataFrame` as well. Previously we pulled them out, modified them and pushed them back, which was kinda ... not required and actually a lot slower.

Speedup add data pt4

---

DESCRIPTION
NEWS.md
R/class-chart-sheet.R
R/class-comment.R
R/class-workbook.R
R/class-worksheet.R
R/wb_load.R
tests/testthat/test-class-comment.R
tests/testthat/test-class-workbook.R
tests/testthat/test-loading_workbook.R
tests/testthat/test-read_sources.R

Just the sort of pull requests I like, touches all sorts of places of code. So it's also cluttered to the max. Joking aside, there is now a new field relships that contains the relationships of a worksheet. This can be addressed and used to manage drawings and vml.

Cleanup drawings and vmlDrawings reference

---

R/wb_load.R

this caused NA conversion warnings and was also wrong 
I'm seeing `NAs introduced by coercion to integer range` with a specifically large workbook. This here is not the issue, but I'm not sure what causes this. The workbook looks fine, but it's to large to check everything.

cleanups in wb_load

---

NEWS.md
R/wb_functions.R
tests/testthat/test-wb_functions.R

Now the following is possible
``` r
add_data(x = t(letters[1:4]), colNames = FALSE)$
add_data(dims = "A3:D6", x = t(matrix(c(1:3, NA_real_), 4, 4)), colNames = FALSE)$
merge_cells(1, rows = 1:2, cols = 1)$
merge_cells(1, rows = 1:2, cols = 2)$
merge_cells(1, rows = 1:2, cols = 3)$
merge_cells(1, rows = 1:2, cols = 4)
wb_to_df(wb, dims = "A2:D4", fillMergedCells = TRUE)
#>   a b c  d
#> 3 1 2 3 NA
#> 4 1 2 3 NA
```
Presumably with large xlsxFiles it is faster to read from a `wbWorkbook` instead of reading from a file.

improve fillMergedCells. closes #324

---

NEWS.md
R/class-workbook.R
R/write.R
tests/testthat/test-wb_styles.R
tests/testthat/test-write.R

@cvaldezerea if you want to have a look, this branch should be much faster than the previous solution. But this is highly experimental and needs some more thinking
We have to avoid duplicated cell entries and should never remove cells that are already available in the workbook. Testing this is highly appreciated.
``` r
mm <- matrix(NA, ncol = 26, nrow = 100)
beg <- Sys.time()
wb <- wb_workbook()$add_worksheet()
wb$add_data(x = mm, colNames = FALSE, na.strings = NULL)
wb$add_fill(dims = "A1:Z100", color = wb_color("yellow"))
end <-  Sys.time()
end - beg
#> Time difference of 0.1001139 secs
beg <- Sys.time()
wb <- wb_workbook()$add_worksheet()
wb$add_fill(dims = "A1:Z100", color = wb_color("yellow"))
end <-  Sys.time()
end - beg
#> Time difference of 0.007579803 secs
beg …
```

create initialize_cell function

---

NEWS.md
R/wb_functions.R
tests/testthat/test-read_from_created_wb.R

The part was moved up in the function and is now before `rowNames` and `colNames`. Therefore it allows reading empty named columns and remove only columns that have no header.
This is a breaking change, because it changes the default behavior of the output. I have nothing against this, but I am not really a user of the `skipEmptyCols`/`skipEmptyRows` argument. Do you have any suggestions @jmbarbone ?

[wb_to_df] modify skipEmptyCols/skipEmptyRows. closes #554

---

NEWS.md
R/RcppExports.R
R/class-workbook.R
R/class-worksheet.R
R/utils.R
R/wb_styles.R
man/create_fill.Rd
man/xml_attr_mod.Rd
src/RcppExports.cpp
src/pugi.cpp
tests/testthat/test-pugixml.R
tests/testthat/test-utils.R
tests/testthat/test-wb_functions.R
tests/testthat/test-wb_styles.R

Needs some real world testing and might be needed in more cases
This brings behavior changes: empty elements will be treated as missing, they wont be written with `xml_node_create()` and are removed from xml strings with `xml_mod_attr()`. Need to check if this is desired or if there are cases where we do not want this.
In `wb_set_selected()` we drop additional arguments because they default to `NULL`. This becomes `""` with `as_xml_attr(NULL)` and will be treated as xml node removal in `xml_mod_attr()`. Previously argument `NULL` would simply be ignored in `xml_mod_attr()` and we probably should think about cases where we pass `NULL` arguments to `xml_mod_attr()`

use as_xml_attr() in wb_styles functions. closes #557

---

DESCRIPTION
NEWS.md
R/readWorkbook.R
inst/WORDLIST
man/read_xlsx.Rd
revdep/README.md

* 2023-04-02: first submission
* 2023-04-02: second submission win builder had a note on a long running example. I have removed the URL example.

release 0.6

---

R/class-workbook.R
tests/testthat/test-class-workbook-wrappers.R

After a bit of head scratching I came up with a solution for the `wb_add_plot()` test.

[test] wb_add_plot()

---

NEWS.md
R/wb_functions.R
man/wb_to_df.Rd
tests/testthat/test-wb_functions.R

``` r
add_data(x = mtcars)$
set_col_widths(cols = c(1, 4, 6, 7, 9), hidden = TRUE)$
set_row_heights(rows = c(3, 5, 8:30), hidden = TRUE)
dat <- wb_to_df(wb, skipHiddenRows = TRUE, skipHiddenCols = TRUE)
dat
#>    cyl disp drat vs gear carb
#> 2    6  160 3.90  0    4    4
#> 4    4  108 3.85  1    4    1
#> 6    8  360 3.15  0    3    2
#> 7    6  225 2.76  1    3    1
#> 31   6  145 3.62  0    5    6
#> 32   8  301 3.54  0    5    8
#> 33   4  121 4.11  1    4    2
```

[wb_to_df] add skipHiddenCols and skipHiddenRows

---

NEWS.md
R/class-comment.R
R/class-workbook-wrappers.R
R/class-workbook.R
man/comment.Rd
man/wbWorkbook.Rd
tests/testthat/test-wb_functions.R

* uses `NULL` as default for `col`/`row`
* uses `dims` argument
* fix `gridExpand = FALSE` (to whom it concerns)
* deprecates the final `xy` argument

[comments] add dims option and minor code cleanup

---

NEWS.md
R/class-workbook.R
R/expect-wrapper.R
man/wbWorkbook.Rd
tests/testthat/test-class-workbook-wrappers.R

I wasn't able to figure out how to fix the `wb_to_df()` wrapper test @jmbarbone . It is commented for now and not all that crucial. I was toying around a little with a `wb` alias, but to no success.
``` r
tmp_xlsx <- temp_xlsx()
wb_workbook()$add_worksheet()$add_data(x = iris)$save(tmp_xlsx)
df <- wb_workbook()$
load(file = tmp_xlsx)$
to_df(dims = "A1:E6")
df
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 2          5.1         3.5          1.4         0.2  setosa
#> 3          4.9         3.0          1.4         0.2  setosa
#> 4          4.7         3.2          1.3         0.2  setosa
#> 5          4.6         3.1          1.5         0.2  setosa
#> 6          5.0         3.6          1.4         0.2  setosa
```

[wbWorkbook] provide wb$load() and wb$to_df()

---

vignettes/openxlsx2_style_manual.Rmd

update style vignette

---

R/class-chart-sheet.R
R/class-workbook.R
R/pugixml.R
R/wb_load.R
man/wbChartSheet.Rd
man/wbWorkbook.Rd
tests/testthat/test-remove_worksheets.R

A couple of cleanups
* add Relationships tag when writing `vml_ref` (took me hours to find that ...!)
* add remaining openxml 2.8.1 fields to wbChartsheet
* enabled chartsheet removal
* fixed a bug, where our worksheet counter got lost: Remove a chartsheet in front of a worksheet and now the worksheet counter resets. This is a nasty one and most likely it is not fixed entirely. Fingers crossed no one will want to remove a sheet in worksheet/chartsheet combinations. Once you know what to look for, it is way to easy to find issues ... #620

Chartsheet cleanup

---

R/class-workbook.R
tests/testthat/test-class-comment.R

[WIP] check for missing files

---

DESCRIPTION
NEWS.md
R/class-workbook.R
R/wb_functions.R
man/wbWorkbook.Rd
man/wb_to_df.Rd
tests/testthat/test-class-workbook.R
tests/testthat/test-date_time_conversion.R
tests/testthat/test-read_sources.R
tests/testthat/test-save.R
tests/testthat/test-wb_functions.R
tests/testthat/test-write.R

When working on #345 I added a new xlsx file to replace many of the older files we use and spotted a faulted behavior in `wb_to_df()`. If `cols` references an empty column, this column is added to the end of the returned data frame. This fixes the behavior.
* added `keep_attributes = FALSE` (most of the time we do not need the `tt` data frame)
* `fillMergedCells` now uses the already loaded workbook object
* Bump R dependency to 3.5.0 as suggested by R check

[wb_to_df] Fix cols

---

.github/workflows/check-standard.yaml
DESCRIPTION
R/testthat-helpers.R

Our tests run in parallel and some files are not yet downloaded. Testthat recommends to name files according to their speed, but maybe we can simply wait until the file is available.

try 100 times

---

NEWS.md
R/utils.R
R/wb_load.R
tests/testthat/test-conditional_formatting.R

If multiple conditional formatting are available for the same range, the `unlist()` part "fixed" the name by attaching a counter at the end of the name.
wb <- wb_load("/tmp/cf.xlsx")
wb$worksheets[[1]]$conditionalFormatting

[wb_load; cf] fix conditional formatting range. closes #646

---

R/class-workbook.R
tests/testthat/test-class-workbook.R

Follow up from #656 . @DavZim I realized that we already had a broken defined names change in `wb_set_sheet_names()`. This should fix our code and might solve your initial issue.

fix named regions

---

R/class-workbook.R
R/helperFunctions.R
tests/testthat/test-class-workbook.R

```R
remotes::install_github("JanMarvin/openxlsx2#669")
df <- data.frame(
Plant = c("A", "C", "C", "B", "B", "C", "C", "C", "A", "C"),
Location = c("E", "F", "E", "E", "F", "E", "E", "G", "E", "F"),
Status = c("good", "good", "good", "good", "good", "good", "good", "good", "good", "bad"),
Units = c(0.95, 0.95, 0.95, 0.95, 0.89, 0.89, 0.94, 0.94, 0.9, 0.9),
stringsAsFactors = FALSE
)
add_worksheet("Data")$
add_data(x = df, startCol = 1, startRow = 2)
df <- wb_data(wb, 1, dims = "A2:D10")
wb$
add_pivot_table(df, dims = "A3", rows = "Plant",
filter = c("Location", "Status"), data = "Units")$
add_pivot_table(df, dims = "A3", rows = "Plant",
filter = c("Location", "Status"), data = "Units",
param = list(numfmts = c(formatCode = "#,###0"), sort_row = …
```

[experimental] Pivot table improvements

---

DESCRIPTION
NEWS.md
R/wb_styles.R
man/create_dxfs_style.Rd
revdep/README.md
revdep/cran.md

* 2023-06-30: First submission
* 2023-06-30: Second submission

Release 0.7.1

---

R/class-workbook.R
R/standardize.R
R/wb_load.R
R/wb_styles.R
R/write_xlsx.R
tests/testthat/test-class-hyperlink.R
tests/testthat/test-class-workbook.R
tests/testthat/test-class-worksheet.R
tests/testthat/test-save.R
tests/testthat/test-standardize.R

At least a warning is returned
``` r
xlsxFile <- system.file("extdata", "openxlsx2_example.xlsx", package = "openxlsx2")
wb1 <- wb_load(xlsxFile)
wb_to_df(wb1, colNames = FALSE, foo = TRUE)
#> Warning in standardize_case_names(...): unused arguments (foo)
#>        B    C  D     E     F          G            H       I        J
#> 2     NA Var2 NA  Var3  Var4       Var5         Var6    Var7     Var8
#> 3   TRUE    1 NA     1     a 2023-05-29 3209324 This #DIV/0! 01:27:15
#> 4   TRUE <NA> NA #NUM!     b 2023-05-23         <NA>       0 14:02:57
#> 5   TRUE    2 NA  1.34     c 2023-02-01         <NA> #VALUE! 23:01:02
#> 6  FALSE    2 NA  <NA> #NUM!       <NA>         <NA>       2 17:24:53
#> 7  FALSE    3 NA  1.56     e       <NA>         <NA>    <NA>     <NA>
#> 8  FALSE …
```

warn on unused arguments in standardize_case_names()

---

vignettes/Update-from-openxlsx.Rmd
vignettes/conditional-formatting.Rmd
vignettes/openxlsx2.Rmd
vignettes/openxlsx2_charts_manual.Rmd
vignettes/openxlsx2_formulas_manual.Rmd
vignettes/openxlsx2_style_manual.Rmd

Remove use of `cols`, and `rows` to use dims instead. Add examples of `wb_dims()` usage. 
Address #681 
I went through the vignettes to see if I could catch some more things.

Update vignettes to latest recommended API.

---

R/baseXML.R
R/class-workbook.R
tests/testthat/test-Workbook_properties.R
tests/testthat/test-aaa.R
tests/testthat/test-class-workbook-wrappers.R

Not sure if this cures #685. Could you have a look @jmbarbone ? Have to say this wrapper test function is still a bit confusing to me.

force datetime creation. closes #685

---

R/class-workbook.R

At least this throws the correct warning and `rowcol_to_dim()` was required, otherwise you get very tiny pictures :smile: 
```R
wb$add_worksheet("Sheet 1", gridLines = FALSE)
require(ggplot2)
p1 <- ggplot(mtcars, aes(x = mpg, fill = as.factor(gear))) +
ggtitle("Distribution of Gas Mileage") +
geom_density(alpha = 0.5)
print(p1) # plot needs to be showing
wb$add_plot(startCol = 4)
```

Fix deprecation code for start_col/start_row. closes #706

---

R/class-chart-sheet.R
R/class-workbook.R
man/wbChartSheet.Rd
man/wbWorkbook.Rd

Addresses #681.
The reason why the documentation did not render properly for `wbWorkbook` is because of issues in roxygen2. namely r-lib/roxygen2#1148 and r-lib/roxygen2#1504
The documentation for `wbWorkbook` and `wbChartSheet looks much better after this PR. 
I looked at how processx documents its `process` R6 Class.
https://github.com/r-lib/processx/blob/main/man/process.Rd and https://github.com/r-lib/processx/blob/main/R/process.R for the record.
Edit: the changes in the R files could be reverted once the roxygen2 fixes are made.
The `wbWorkbook` docs could be even cleaner if some documentation of fields was removed ? i.e. see methods first? Also could add links to vignettes on how to use it, although, it is mentioned in many places, how to use the R6 methods, `wb$add` etc. (for …

Improve `wbWorkbook` documentation.

---

NEWS.md
R/read.R
R/wb_load.R
tests/testthat/test-date_time_conversion.R
tests/testthat/test-named_regions.R

⚠️ Previously `wb_to_df()` was not using `date1904` detection, hence conversions via `wb_to_df()` were always assuming an origin of `1900-01-01` contrary to `1904-01-01`. This file setting is somewhat exotic and we did provide tools to let the user detect the error, it is nevertheless a shameful mistake. Sorry.
``` r
DATE  <- as.Date("2015-02-07") + -10:10
POSIX <- as.POSIXct("2022-03-02 19:27:35") + -10:10
time <- data.frame(DATE, POSIX)
tmp <- temp_xlsx()
wb$workbook$workbookPr <- '<workbookPr date1904="true"/>'
wb$add_worksheet()$add_data(x = time)
wb$save(tmp)
wb_to_df(wb) %>% head()
#>         DATE               POSIX
#> 2 2015-01-28 2022-03-02 19:27:25
#> 3 2015-01-29 2022-03-02 19:27:26
#> 4 2015-01-30 2022-03-02 19:27:27
#> 5 2015-01-31 …
```

[wb_to_df] fix date1904 conversion

---

R/class-chart-sheet.R
R/class-workbook.R
R/class-worksheet.R
man/wbChartSheet.Rd
tests/testthat/test-class-worksheet.R

As reported in #749 
it is now possible to pass wb_color(theme).

restore and improve tab_color

---

NEWS.md
R/class-workbook-wrappers.R
R/openxlsx2-package.R
man/openxlsx2_options.Rd
man/wb_add_pivot_table.Rd
vignettes/conditional-formatting.Rmd
vignettes/openxlsx2_charts_manual.Rmd
vignettes/openxlsx2_formulas_manual.Rmd
vignettes/openxlsx2_style_manual.Rmd

This just aims to rename vignettes + tweaks news close #761 
Now: 
This PR:

Vignette names

---

R/class-workbook.R

This fixes a typo and allows adding formulas with [`equatags`](https://github.com/ardata-fr/equatags/tree/main):
```R
eqs <- c(
"(ax^2 + bx + c = 0)",
"a \\ne 0",
"x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}")
fml_xml <- function(x) {
x <- equatags::transform_mathjax(x, to = "mml")
x <- read_xml(x, pointer = FALSE)
out <- sprintf('
<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
<xdr:absoluteAnchor>
<xdr:from>
<xdr:col>1</xdr:col>
<xdr:colOff>482600</xdr:colOff>
<xdr:row>1</xdr:row>
<xdr:rowOff>63500</xdr:rowOff>
</xdr:from>
<xdr:to>
<xdr:col>13</xdr:col>
<xdr:colOff>685800</xdr:colOff>
<xdr:row>29</xdr:row>
<xdr:rowOff>25400</xdr:rowOff>
</xdr:to>
<mc:AlternateContent …
```

[wb_add_drawing] read and add "mc:alternateContent"

---

src/xlsb.cpp
src/xlsb_funs.h

This does not fix my test files, but at least they are no longer crashing.
Obviously some old gov files with lots of formulas:
https://webarchive.nationalarchives.gov.uk/ukgwa/20150603214536/http:/www.ofwat.gov.uk/pricereview/pr14/prs_web201405popfinancialmodel

[xlsb] avoid hard to spot crash with unhandled array formulas

---

R/class-workbook.R
tests/testthat/test-remove_worksheets.R

Could you please double check with your files that it works as expected @chowmun63?
```R 
remotes::install_github("JanMarvin/openxlsx2#793)
```
The issue was that the last tab was active, but removed and the activeTab id was never updated. Therefore Excel complained.

[remove_worksheet] update activeTab. closes #792

---

R/helper-functions.R
tests/testthat/test-class-workbook.R

Forgot to push this
```R
wb <- wb_workbook() %>% wb_add_worksheet() %>% wb_add_data(x = mtcars)
df <- wb_data(wb, sheet = 1)
wb <- wb %>%
wb_add_pivot_table(df, dims = "A3",
filter = "am", rows = "cyl", cols = "gear", data = "disp",
params = list(sort_item = list(gear = c(3, 2, 1)))
)
```

[pivot_table] add sort_item param option

---

R/class-workbook-wrappers.R
R/class-workbook.R
man/properties.Rd
man/wbWorkbook.Rd
man/wb_workbook.Rd
tests/testthat/test-class-workbook-wrappers.R
tests/testthat/test-loading_workbook.R

This also adds more tests and cleans up the previous changes to properties
File properties fields Manager and Company are part of `wb$app`:
```r
wb$app[c("Company", "Manager")]
#> $Company
#> [1] "<Company>COMPANY</Company>"
#> 
#> $Manager
#> [1] "<Manager>MANAGER</Manager>"
```
We could add these to our set/get properties, but I don't use file properties at all and will not prepare a pull request for this.

[properties] get/set keywords and comments

---

DESCRIPTION
tests/testthat/helper.R
tests/testthat/test-aaa.R
tests/testthat/test-class-comment.R

Previously all files were downloaded prior to testing. Now the download is triggered by testfile_path(). This allows restoring parallel tests.

[tests] improve testfile_path() to download files 

---

R/class-workbook.R
R/wb_load.R

This PR provides the safe part from #780
*  `is_wbWorkbook()` and 
*  allows to set `sheet = NULL` in `wb_load()`
This is helpful to load a workbook without any sheet information. Think of it like this, you want only the sheet names in a hundred MB size xlsx file. Obviously you should be able to load all the sheets, but you shouldn't have to. The worksheet information is in `workbook.xml` so you do not need anything else. With this PR you can do the following:
```R
wb_load(x, sheet = NULL, data_only = TRUE)
```
Ideally this should be used in a few functions to restore a few `openxlsx` workflows like this - as suggested in our README
> Furthermore, there are several ways to read certain information of an openxml spreadsheet without having opened it in a spreadsheet software before, e.g. to …

[wb_load] minimal workbook

---

R/class-workbook-wrappers.R
R/class-workbook.R
R/helper-functions.R
inst/WORDLIST
man/wbWorkbook.Rd
man/wb_clone_worksheet.Rd
tests/testthat/test-cloneWorksheet.R

Early attempt at #380
There are a couple of things to do and this is just a first step
* copy elements
* update copy elements
Hopefully we can build on `wb_clone_worksheet()`, but even then there is still a lot to do.
```R
fl <- system.file("extdata", "oxlsx2_sheet.xlsx", package = "openxlsx2")
wb_in <- wb_load(fl)
add_worksheet("NOT_SUM")$
add_data(x = head(iris))$
add_fill(dims = "A1:B2", color = wb_color("yellow"))$
add_border(dims = "B2:C3")
wb$add_worksheet("SUM")
wb$worksheets[[2]] <- wb_in$clone(deep = TRUE)$worksheets[[1]]
wb$sharedStrings <- wb_in$sharedStrings
wb$append("Content_Types", "<Override PartName=\"/xl/sharedStrings.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml\"/>")
wb$append("workbook.xml.rels", …
```

[clone_worksheet] copy worksheet across workbooks

---

tests/testthat/test-class-comment.R
tests/testthat/test-class-workbook-wrappers.R
tests/testthat/test-class-worksheet.R
tests/testthat/test-loading_workbook.R
tests/testthat/test-named_regions.R
tests/testthat/test-standardize.R
tests/testthat/test-utils.R
tests/testthat/test-write.R
tests/testthat/test-writing_posixct.R

I always assumed that the options are only valid for a single testthat chunk, but they are not and therefore some were carried over the entire test run

[tests] cleanup options

---

tests/testthat/helper.R

Found running local R CMD check --as-cran

Skip testfile_path() tests on cran.

---

R/class-workbook.R

adding a drawing to a worksheet should not overwrite existing worksheet_relationships like pivot tables

[drawing] do not overwrite worksheet relationships

---

NEWS.md
R/class-workbook-wrappers.R
R/helper-functions.R
man/wb_add_pivot_table.Rd

```r
wb <- wb_workbook() %>% wb_add_worksheet() %>% wb_add_data(x = mtcars)
df <- wb_data(wb, sheet = 1)
wb <- wb %>%
wb_add_pivot_table(
df,
dims = "A3",
filter = "am",
rows = "cyl",
cols = "gear",
data = "disp",
params = list(
show_data_as = c("percentOfRow"),
numfmts = c(formatCode = "#.##%")
)
)
```

[pivot tables] add `show_data_as` and `compact`/`outline`

---

NEWS.md
R/write.R
tests/testthat/test-formulas.R

This solves an issue described in this [SO](https://stackoverflow.com/q/77379858/12340029) thread. Previously data frame formulas were not xml escaped.
``` r
df_tmp <- data.frame(
f = paste0("'A&B'!A1")
)
class(df_tmp$f) <- c(class(df_tmp$f), "formula")
add_worksheet("A&B")$
add_worksheet("Fml")$add_data(x = df_tmp, col_names = FALSE)
```

[write_data] escape all formulas in write_data

---

R/helper-functions.R
tests/testthat/test-class-workbook.R

Now the following works
``` r
wb <- wb_workbook() %>% wb_add_worksheet() %>% wb_add_data(x = mtcars, inline_strings = F)
df <- wb_data(wb)
wb$add_pivot_table(
df,
rows = c("cyl", "mpg"),
cols = c("vs","gear"),
data = c("disp", "hp"),
fun  = c("sum", "average"),
params = list(
apply_alignment_formats    = TRUE,
apply_number_formats       = TRUE,
apply_border_formats       = TRUE,
apply_font_formats         = TRUE,
apply_pattern_formats      = TRUE,
apply_width_height_formats = TRUE,
auto_format_id             = 4099,
data_caption               = "Foo"
)
)
```

[pivot tables] use standardize_case_names() and as_xml_attr()

---

NEWS.md
R/baseXML.R
R/class-workbook.R
R/class-worksheet.R
inst/WORDLIST
tests/testthat/test-class-workbook.R

This fixes a bug with relationship ids. If the sheet already contains drawings and some of these drawings have been removed, try to get the next free relationship id and do not duplicate existing relationship ids.
Also this PR improves the unfold_cols() code so that the column widths selection is now faster in some corner cases.
``` r
tabelapronta <- structure(
list(
Data = c(45224, 45224, 45224, 45224, 45224, 45224, 45224, 45224, 45224, 45224),
Estado = c("ms", "ms", "ms", "ms", "ms", "ms", "ms", "ms", "ms", "ms"),
`Município` = c("campo-grande", "campo-grande", "campo-grande", "campo-grande", "campo-grande", "campo-grande", "campo-grande", "campo-grande", "campo-grande", "campo-grande"),
`Endereço` = c("Avenida Rachid Neder", "Rua Quinze de Novembro", "Rua Brisas de …
```

[drawings] improve relationship id selection

---

R/class-workbook.R
R/helper-functions.R

Works in Libreoffice
ping @vorpalvorpal
``` r
example_df <- data.frame(
type = c("EU", "US", "US", "EU", "EU", "EU"),
location = c("London", "NYC", "NYC", "Berlin", "Madrid", "London"),
amount = c(7, 5, 3, 2.5, 6, 1)
)
wb <- wb_workbook() %>% 
wb_add_worksheet() %>% 
wb_add_data(x = example_df)
df <- wb_data(wb)
wb <- wb %>%
wb_add_pivot_table(
df, dims = "A3", rows = "location", filter = "type", data = "amount",
slicer = "location", pivot_table = "pt1",
param = list(
choose = c(type = 'x=="EU"', 
location = 'x %in% c("London", "Madrid")')
)
)
```

[pt] add choose param

---

R/class-workbook.R
tests/testthat/test-cloneWorksheet.R

``` r
wb_in <- wb_load("https://github.com/JanMarvin/openxlsx-data/raw/main/Single_hyperlink.xlsx")
dat <- wb_data(wb_in, 1, dims = "A1:B2", col_names = FALSE)
wb_in$copy_cells(data = dat, dims = "A3")
dat <- wb_data(wb_in, 1, dims = "A1:B3", col_names = FALSE)
wb_in$copy_cells(data = dat, dims = "D1", transpose = TRUE)
if (interactive()) wb_in$open()
```

[copy_cells] copy hyperlinks and fix handling of transposed cells. fixes #846

---

NEWS.md
R/class-comment.R
R/class-workbook.R
R/conditional_formatting.R
R/converters.R
R/openxlsx2-package.R
R/write.R
R/write_xlsx.R
man/openxlsx2_options.Rd

Follow-up to #848., where support for `maxWidth` and `minWidth` was added.
Related to #20

Document options

---

NEWS.md
R/baseXML.R
R/class-comment.R
R/class-workbook-wrappers.R
R/class-workbook.R
man/comment_internal.Rd
man/wbWorkbook.Rd
man/wb_add_comment.Rd
man/wb_add_pivot_table.Rd
tests/testthat/test-class-comment.R
tests/testthat/test-class-workbook.R

```R
wb$add_worksheet("Sheet 1")
c1 <- wb_comment(text = "this is a comment", author = "", visible = TRUE)
wb$add_comment(dims = "B10", comment = c1)
c2 <- wb_comment(text = "this is another comment", author = "Marco Polo")
wb$add_comment(sheet = 1, dims = "C10", comment = c2)
s1 <- create_font(b = "true", color = wb_color(hex = "FFFF0000"), sz = "12")
s2 <- create_font(color = wb_color(hex = "FF000000"), sz = "9")
c3 <- wb_comment(text = c("This Part Bold red\n\n", "This part black"), style = c(s1, s2))
wb$add_comment(sheet = 1, dims = wb_dims(3, 6), comment = c3, color = wb_color("green"))
```

[wb_comment] modify the background color. closes #869

---

NEWS.md
R/RcppExports.R
R/openxlsx2-package.R
R/write.R
man/openxlsx2_options.Rd
src/RcppExports.cpp
src/helper_functions.cpp
src/openxlsx2_types.h
tests/testthat/test-helper-functions.R
vignettes/openxlsx2_style_manual.Rmd

This is set by default to the local currency of the spreadsheet software. For other cases, a predefined numeric style should be used. Have not seen a local variable to apply defining the currency used.
Adds the internal helper `is_charnum()` to check if a string can be safely converted to a numeric value.
``` r
df <- data.frame(
"dollar" = paste("$", 1:20),
"euro" = 1:20
)
class(df$dollar) <- c("currency", class(df$dollar))
class(df$euro) <- c("currency", class(df$euro))
str(df)
#> 'data.frame':    20 obs. of  2 variables:
#>  $ dollar: 'currency' chr  "$ 1" "$ 2" "$ 3" "$ 4" ...
#>  $ euro  : 'currency' int  1 2 3 4 5 6 7 8 9 10 ...
add_data(x = df, start_row = 4, row_names = FALSE)$
add_data_table(x = df, …
```

[Styles] restore currency style. fixes #878

---

DESCRIPTION
NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/helper-functions.R
man/wb_add_pivot_table.Rd

``` r
wb <- wb_workbook() %>% wb_add_worksheet() %>% wb_add_data(x = mtcars)
df <- wb_data(wb, sheet = 1)
wb <- wb %>%
wb_add_pivot_table(
df, 
dims = "A3",
cols = NULL,
rows = "vs",
data = c("disp", "cyl", "=cyl/disp" = "Field1", "=Field1 * _xlfn.UNIQUE(am)" = "Rand"),
param = list(
numfmt = c(
formatCode = c("#,##0.0"),
formatCode = c("#,##0.0"),
formatCode = c("0.0%"),
formatCode = c("0.0%")
)
)
)
```

[pt] calculate pivot table field with formula

---

R/wb_load.R
tests/testthat/test-loading_workbook.R

[load] better error message for zip compressed input files. closes #896

---

NEWS.md
R/write_xlsx.R
tests/testthat/test-save.R

Sometimes it is a good idea to have a look at the coverage ...

[write_xlsx] restore first_active_{col,row} and first_{col,row}

---

R/class-workbook.R
R/helper-functions.R
tests/testthat/test-helper-functions.R

works now. first part of #909 
``` r
dd <- data.frame(Foo = 1, foo = 2, bar = 2)
wb <- wb_workbook()$add_worksheet()$add_data(x = dd)
pt <- wb_data(wb)
wb$add_pivot_table(pt, cols = "Foo", data = "bar")
```

[pt] fix non distinct names in wb_data object

---

R/helper-functions.R
tests/testthat/test-class-workbook.R

Apparently #842 was not yet sufficient. second part of #909
``` r
dd <- data.frame(Foo = sample(0:1, 26, TRUE), foo2 = letters, bar = TRUE)
wb <- wb_workbook()$add_worksheet()$add_data(x = dd)
pt <- wb_data(wb)
wb$
add_pivot_table(pt, rows = "foo2", data = "bar",
pivot_table = "pt1",
params = list(
sort_item = list(foo2 = c("b", "e", "d"))
))$
add_slicer(pt, slicer = "foo2", pivot_table = "pt1", dims = "A10",
params = list(
choose = c(foo2 = 'x %in% c("b", "e", "d")')
))
```

[pt] another attemt to fix item sorting

---

R/class-workbook.R
R/helper-functions.R

Not sure about the extLst. Is it always there? Third part of #909
Allows something like this:
``` r
wb <- wb_workbook()$add_worksheet()$add_data(x = mtcars)
pt <- wb_data(wb)
wb$
add_pivot_table(
pt, 
cols = c("am", "carb"),
data = "disp",
params = list(
subtotal_top = FALSE,
default_subtotal = FALSE,
rowGrandTotals = FALSE,
colGrandTotals = FALSE,
compact = FALSE,
compact_data = FALSE,
outline = FALSE
)
)
```

[pt] disable subtotals

---

R/baseXML.R
R/converters.R
R/utils.R
R/write.R
tests/testthat/test-class-workbook.R
tests/testthat/test-converters.R
tests/testthat/test-utils.R
tests/testthat/test-write.R

fixes `wb_add_data(with_filter = TRUE)` for multiple worksheets

[tests increase coverage

---

R/class-style_mgr.R
R/class-workbook-utils.R
R/class-workbook.R
R/converters.R
R/helper-functions.R
R/pivot_table.R
R/pugixml.R
R/utils.R
R/wb_functions.R
R/write.R
R/write_xlsx.R
tests/testthat/helper.R
tests/testthat/test-conditional_formatting.R

may improve (very) slightly performance. (Split from #922)

code lints

---

R/class-workbook-utils.R
R/write.R
tests/testthat/test-class-workbook.R
tests/testthat/test-tables.R

Partial matching + table name error message.

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/helper-functions.R
R/write.R
R/write_xlsx.R
inst/WORDLIST
man/wbWorkbook.Rd
man/wb_add_data_table.Rd
man/wb_add_formula.Rd
man/write_datatable.Rd
man/write_xlsx.Rd
tests/testthat/test-write.R

Inspired by https://github.com/ycphs/openxlsx/issues/464
``` r
add_data_table(
x = as.data.frame(USPersonalExpenditure), 
row_names = TRUE,
total_row = c(text = "Total", "none", "sum", "sum", "sum", "SUM")
)
```

[write] add total_row option to wb_add_data_table()

---

NEWS.md
R/class-workbook.R
R/utils.R
man/wbWorkbook.Rd
man/wb_dims.Rd
tests/testthat/test-utils.R
vignettes/openxlsx2_style_manual.Rmd

Addresses part of https://github.com/JanMarvin/openxlsx2/pull/958#discussion_r1501437063
I made `from_dims` independant from `from_col` / `from_row`, but didn't really document it. Hopefully the error should be clear enough?

Add from_dims to wb_dims

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/openxlsx2-package.R
R/write.R
R/write_xlsx.R
man/openxlsx2-deprecated.Rd
man/openxlsx2_options.Rd
man/wb_add_data.Rd
man/wb_add_data_table.Rd
man/write_data.Rd
man/write_datatable.Rd
man/write_xlsx.Rd
tests/testthat/test-options.R

I was thinking about something more like this.
I strongly feel about not having an option overriding a parameter passed (other than the default)
If option is set and na.string is  not supplied: use the option
If option is set and na.string is supplied: use na.strings
If option is not set and na.string is not use default.
Amends to #473 and addresses #20

Add openxlsx2.na.strings option

---

NEWS.md
R/class-workbook-wrappers.R
R/helper-functions.R
R/write.R
inst/WORDLIST
man/wb_add_formula.Rd
src/helper_functions.cpp
tests/testthat/test-write.R

This introduces a change in behavior when writing vectors. Previously, we simply ignored whichever direction `dims` requested. We just selected the top left corner and started writing from there. This PR changes that. We now use the direction that `dims` suggests:
* `A1` (the default) or `A1:A2` - vertical
* `A1:B1` - horizontal
and we transpose the vector so that it can be written horizontally. This affects vectors, formulas (#972) and hyperlinks.
The break occurs if a user has previously transposed a vector manually and also specified the direction via `dims`. In this case, the data is transposed twice and the output looks different with the pull request, see the first example.
``` r
add_data(x = 1:2, dims = "A1:B1")$
add_data(x = …
```

[write] dims impact the direction vectors are written

---

R/class-workbook.R

caught with options..
Lmk if this is correct or if I missed something!
```r
options(
warnPartialMatchArgs = TRUE,
warnPartialMatchDollar = TRUE,
warnPartialMatchAttr = TRUE
)

Avoid partial matching

---

NEWS.md
R/utils.R
tests/testthat/test-utils.R

Addresses https://github.com/JanMarvin/openxlsx2/issues/988#issuecomment-2051976050
Doing some touchups locally!

fix corner cases of wb_dims + standardize error messages

---

src/helper_functions.cpp

> Dear maintainer,
>
> Please see the problems shown on
>[<https://cran.r-project.org/web/checks/check_results_openxlsx2.html>](https://cran.r-project.org/web/checks/>check_results_openxlsx2.html).
>
>Please correct before 2024-05-04 to safely retain your package on CRAN.
>
>The CRAN Team
```R
Result: NOTE
File ‘openxlsx2/libs/openxlsx2.so’:
Found non-API call to R: ‘Rf_isBlankString’
Compiled code should not call non-API entry points in R.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

use `Rf_isBlankString()`

---

NEWS.md
R/RcppExports.R
R/class-workbook-wrappers.R
R/class-workbook.R
R/utils.R
R/wb_functions.R
R/write.R
man/dataframe_to_dims.Rd
man/dims_helper.Rd
man/wbWorkbook.Rd
man/wb_add_data.Rd
man/wb_add_formula.Rd
man/write_data.Rd
man/write_formula.Rd
src/RcppExports.cpp
src/helper_functions.cpp
tests/testthat/test-utils.R
tests/testthat/test-wb_functions.R

Still a little hackish solution to the flexibility problem mentioned in #796 , but it shows what is possible. For whatever reason the enforce option does not work with `wb_add_fill()` probably because empty cells are still initialized even though they are not filled.
Also there is still a bug, for now I simply assumed that all data columns are beneath each other to fill their positions. In the example below the column header is right to the data and hence the row has to be filled wider, which is not yet implemented. Hence the first data part is filled incorrectly.
``` r
add_fill(dims = "A1:B2;C3:D4;E1:F2;G5:H6;I2:K2", color = wb_color("yellow"))
options("openxlsx2.enforce_dims" = TRUE)
wb$add_data(dims = "I2:J2;A1:B2;G5:H6", x = …
```

[WIP] More flexible dims

---

NEWS.md
R/class-workbook.R
R/read.R
R/wb_functions.R
R/write.R
man/dims_to_dataframe.Rd
tests/testthat/test-wb_functions.R

if rows and columns were entirely omitted. This could create a cc object that was to short. fixes #1014

[dims] previously non-consecutive dims could get lost

---

src/strings_xml.cpp
tests/testthat/test-strings_xml.R

This was triggered by some SAS exported xlsx file which has:
```XML
<c r="A1" t="inlineStr"/>
```

[misc] avoid cryptic error on blank inline string. fixes #1038

---

R/class-workbook.R
src/xlsb.cpp
src/xlsb_defines.h
src/xlsb_funs.h

This fixes formulas like:
`SUM({1,2,3;4,5,6})`
Works now too:
`SUMIFS(A1:A2,foo!B2:B3,{"A"})`
Because of the reference at another worksheet, the formula is broken. Probably something in `RevExtern`.

[xlsb] fix more array fmls

---

R/class-workbook.R
R/utils.R
R/wb_functions.R
tests/testthat/test-utils.R

Fix #843
This PR extends `wb_dims()` to accept multiple columns:
``` r
wb <- wb_workbook() %>% 
wb_add_worksheet() %>% 
wb_add_data(x = mtcars) %>% 
wb_add_fill(dims = wb_dims(x = mtcars, cols = c("cyl", "gear"), select = "col_names"), color = wb_color("blue")) %>% 
wb_add_fill(dims = wb_dims(x = mtcars, cols = c("cyl", "gear")), color = wb_color("orange"))
if (interactive())  wb %>% wb_open()
```
``` r
wb_dims(x = mtcars, cols = c("cyl"))
#> [1] "B2:B33"
wb_dims(x = mtcars, cols = c("cyl", "gear"))
#> [1] "B2:B33,J2:J33"
wb_dims(x = mtcars, select = "col_names")
#> [1] "A1:K1"
wb_dims(x = mtcars, cols = c("cyl", "gear"), select = "col_names")
#> [1] "B1,J1"
```

[dims] extend wb_dims() to accept multiple columns

---

R/utils.R
tests/testthat/test-wb_styles.R

```R
wb <- wb_workbook()$add_worksheet()
new_fill <- create_fill(patternType = "solid", fgColor = wb_color(hex = "FF334E6F"))
wb$styles_mgr$add(new_fill, "new_fill")
xf <- create_cell_style(fill_id = wb$styles_mgr$get_fill_id("new_fill"))
wb$styles_mgr$add(xf, "xf")
wb$set_cell_style(
dims = "A1:A2", 
style = wb$styles_mgr$get_xf_id("xf")
)
wb$set_cell_style(
dims = c("B1", "B2"), 
style = wb$styles_mgr$get_xf_id("xf")
)
```
Edit: This results in an error in 1.7 if the cell is uninitialized

[dims] fix unhandled condtion

---

src/xlsb.cpp
src/xlsb_funs.h
tests/testthat/test-read_xlsb.R

Unfortunately it looks like we have to implement all `PtgTypes` to be able to read formulas without surprises. The question seems to be, how do I construct formulas that trigger these conditions. Blindly adding seems like a last resort

[xlsb] read PtgMemErr

---

R/wb_load.R
src/xlsb.cpp
src/xlsb_defines.h
src/xlsb_funs.h
tests/testthat/test-read_xlsb.R

I have a broken test file from here: https://github.com/SheetJS/test_files/blob/master/calendar_stress_test.xlsb
Not sure why, but if I read the file as is, it reads just fine. Once the end of the file is reached, it tries to read
* `BrtFRTBegin` - fine whatever
* `BrtCellBlank`  - it looks like something went wrong
* `BrtRowHdr`    - ???
and here it errors out, because there is no row. I guess the file is damaged. Because the maximal amount of rows was reached Excel might have ended the file saving prematurely and it's only able to read the file, because it does some additional checks. After all, if I read the file with Excel in MS365 and save it as xlsx first and then again as xlsb, `openxlsx2` is able to read the file just fine.
Why do I write this? Because I wanted to read the data …

[xlsb] add data validations

---

tests/testthat/test-class-comment.R
tests/testthat/test-class-workbook.R
tests/testthat/test-outlines.R
tests/testthat/test-page_setup.R
tests/testthat/test-pugi_cpp.R
tests/testthat/test-pugixml.R
tests/testthat/test-read_sources.R
tests/testthat/test-wb_functions.R
tests/testthat/test-wb_styles.R
tests/testthat/test-write.R

just because I now (almost) know how to use git and like this way too much

Unrelated lints to tests

---

R/RcppExports.R
R/utils.R
R/wb_functions.R
src/RcppExports.cpp
src/helper_functions.cpp

``` r
n <- 5e5
data1 <- data.frame(
T1 = rep("test", n),
T2 = rep("test", n),
T3 = rep(as.POSIXct("2024-01-01"), n),
T4 = rep(as.POSIXct("2024-01-01"), n)
)
data2 <- data.frame(
T1 = rep("test", n),
T3 = rep(as.POSIXct("2024-01-01"), n),
T2 = rep("test", n),
T4 = rep(as.POSIXct("2024-01-01"), n)
)
fun <- function(x) {
wb_workbook()$
add_worksheet(
sheet = "test",
grid_lines = FALSE
)$
add_data(
sheet = "test",
x = x,
na.strings = ""
)
}
res <- microbenchmark::microbenchmark(
fun(data1)
,
fun(data2)
,
times = 5
)
#> Warning in microbenchmark::microbenchmark(fun(data1), fun(data2), times = 5):
#> less accurate nanosecond times to avoid potential integer overflows
```
``` r
res
#> Unit: seconds
#>        expr      min       lq     mean   median       uq      max neval
#> …
```

[dims] code cleanup

---

src/helper_functions.cpp
tests/testthat/test-tables.R

The condition is somehow triggered by factor variables. Our logic tries to convert this to strings, but it somehow goes a little further and tries to write column headers as numbers too. This breaks in a table, because table headers require character type colnames.

[write] table column names have to be characters

---

DESCRIPTION
NEWS.md
R/utils.R
R/wb_functions.R
man/convert_date.Rd

* First submission: 2024-07-05
```
Dear CRAN team,
we are aware of the NOTE regarding the use of STRING_PTR. This is caused by the Rcpp package and will be addressed with updates to Rcpp.
Best regards,
Jan Marvin Garbuszus
```

Release 1.8

---

DESCRIPTION
NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/write.R
man/wbWorkbook.Rd
man/wb_add_formula.Rd
tests/testthat/test-formulas.R
tests/testthat/test-wb_functions.R

``` r
df <- data.frame(
x = 1:5,
y = 1:5 * 2
)
wb <-  wb_workbook()$add_worksheet()$add_data(x = df)
wb$add_formula(
x      = "=A2/B2",
dims   = "C2:C6",
shared = TRUE
)
wb$add_formula(
x      = "=A$2/B$2",
dims   = "D2:D6",
shared = TRUE
)
```

[fml] create shared formulas

---

NEWS.md
R/utils.R
tests/testthat/test-utils.R

The output still returns ranges, but that's acceptable. We should be able to catch this and should be able to return `A1:A1` as `A1`.

[wb_dims] without `x` and non sequential rows, incorrect results were returned. fixes #1093

---

R/read.R
R/wb_functions.R
tests/testthat/test-cloneWorksheet.R
tests/testthat/test-read_xlsb.R

``` r
df <- data.frame(
x = 1:3, y = 1:3,
z = paste(paste0("A", 1:3 + 1L), paste0("B", 1:3 + 1L), sep = "+"),
stringsAsFactors = FALSE
)
class(df$z) <- c(class(df$z), "formula")
add_data(x = df)
x <- wb_to_df(wb, show_formula = TRUE)
wb$add_worksheet()$
add_data(x = x)
```

[wb_to_df] create type `f` when reading formula

---

.Rbuildignore
vignettes/openxlsx2_style_manual.Rmd

I noticed that this image alone had 500 kb. 
Here is an approachto include this image only on pkgdown, but not on CRAN.
The cf images are pretty small around 30kb on average.

Avoid adding the worksheet styling image on the CRAN vignette

---

NEWS.md
R/converters.R
R/utils.R
man/openxlsx2-package.Rd
tests/testthat/test-converters.R
tests/testthat/test-utils.R

Attempt to address partially #1104, by getting rid of some bugs?
This doesn't really work.
Previously, there was a large condition that would just evaluate the `below` `above`, `left`, `right` code if `from_dims` was supplied.
This doesn't yet work, but I think it is a start.

Wb dims bug

---

R/class-workbook.R
R/openxlsx2-package.R
man/openxlsx2_options.Rd

Could you please double check @olivroy , I fixed a typo in `compressionlevel` (previously with three `s`, therefore no `l`). If you have a smarter solution at hand, I'm all ears :)
This looks kinda strange in comparison
```R
getOption("openxlsx2.compressionlevel", getOption("openxlsx2.compresssionevel", 6L))
```
[Edit] updated for the missing `l`

[misc] document compression level option. closes #1113

---

R/utils.R
tests/testthat/test-utils.R

This breaks a few previously valid cases, where we were working around broken input. The basic idea is that we have a single dim that can be reduced with selections of columns or rows and moved around in positive ranges.

[dims] simplify `wb_dims()`. fixes #1124

---

vignettes/openxlsx2_charts_manual.Rmd

As discussed in https://github.com/yihui/knitr/issues/2338 this solves #1073.
Unfortunately, I can't say I fully understand the problem (and I can't say I'm a big fan of a certain party making everyone's life harder by letting people figure it out for themselves). 
If the environment variable `_R_CHECK_VIGNETTES_SKIP_RUN_MAYBE_` is `false`, for some reason `R CMD check openxlsx2_*` throws an error with the chart vignette in sections containing `ggplot2` (and `print()`). I assume this is somehow due to the fact that the `print()` statement is not available in non-interactive mode and another option would be to look for `interactive()`? Anyway, this problem is hidden with `R CMD check --as-cran openxlsx2_*`, which disables `knitr::purl()`.
Now for some reason the CRAN oldrel Macs are …

[vignette] add `purl = FALSE` to chunks using `ggplot2`. fixes #1073

---

DESCRIPTION
NEWS.md
README.Rmd
README.md
vignettes/conditional-formatting.Rmd

* First submission: 2024-09-07
* Second submission: 2024-09-07 (re-submission due to a failure to download a file from github in the CRAN incoming debian server)

Release 1.9

---

DESCRIPTION
NEWS.md
R/write.R
tests/testthat/test-formulas.R

If dims is a single cell and formula is larger than a single cell

[formula] Restore extending single cell dims for `wb_add_formula()`. fixes #1130

---

NEWS.md
R/utils.R
tests/testthat/test-utils.R

fixes a regression in `wb_dims` that caused overflow errors resulting in a failing check for valid column input.

[dims] column names should not be evaluated. fixes #1132

---

NEWS.md
src/write_file.cpp
tests/testthat/test-save.R
tests/testthat/test-write.R

This PR skips blank cells entirely as discussed in #1110 .
This reduces the file size significantly for the example data provided and other sparse matrices that are thrown at `openxlsx2`, but due to possible faulty impacts, this is still unlikely to be added without extensive testing.
Maybe merge after the next release or never.

[write] skip blanks

---

NEWS.md
R/baseXML.R
R/class-workbook-wrappers.R
R/class-workbook.R
R/helper-functions.R
inst/AUTHORS
inst/WORDLIST
man/wbWorkbook.Rd
man/wb_add_image.Rd
tests/testthat/test-read_sources.R
tests/testthat/test-write.R

@jistria I took the liberty to convert your PR to `openxlsx2`

[image] add address argument to `wb_add_image()`

---

R/class-workbook-wrappers.R
R/class-workbook.R
man/wbWorkbook.Rd
man/wb_add_hyperlink.Rd
tests/testthat/test-class-hyperlink.R
tests/testthat/test-class-workbook-wrappers.R

Check that a hyperlink is present

[hl] helper to remove hyperlinks

---

R/class-workbook.R
R/get-named-regions.R

* This ~~improves~~ impacts `flexlsx`, which makes a lot of use of `wb_add_border()` which is calling `wb_get_cell_style()` internally
* Move internal functions out of `wbWorkbook` object. Move functions to the top of the page (I read from top to bottom) and remove no longer exported and unused functions (`is_wbWorkbook()` and `wb_get_sheet_name()`

[styles] speedup `wb_get_cell_style()`

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
inst/AUTHORS
man/properties-wb.Rd
man/wbWorkbook.Rd
man/wb_workbook.Rd
tests/testthat/test-loading_workbook.R

I want to have openxlsx2 reset the authorship dates of my manually-generated test file to a default date, so that
it only shows up in git when its contents are saved and not when I do a save in excel without changes.
I could not do it because openxlsx2 automatically resets the create_date to the current time and does not have
a way of setting the modified date. This patch:
* Stops openxlsx2 from setting the create date with every call to `wb_set_property()`. Only in `wb_workbook()`, the current date is set as default create date
* Allows to manually set the last modified date

Add modify date, don't auto-change create date

---

NEWS.md
R/wb_functions.R
tests/testthat/test-wb_functions.R

`dims = "A1:A5,C1:D5"` behaves similar to `dims = "A1,C1:D1,A2:A5,C2:D5"`

[wb_to_df] make equal sized non consecutive dims behave similar to unequal sized non concsecutive dims.

---

NEWS.md
R/openxlsx2-package.R
R/write.R
src/helper_functions.cpp
src/openxlsx2.h
src/openxlsx2_types.h
tests/testthat/test-write.R

Previously this was only documented but did nothing

[write] restore `sep` functionality. closes #1199

---

R/class-workbook.R
R/wb_load.R
tests/testthat/test-read_sources.R

``` r
xlsx_path <- system.file("extdata", "openxlsx2_example.xlsx", package = "openxlsx2")
xslx_path <- tempfile(fileext = ".xslx")
file.copy(xlsx_path, xslx_path)
#> [1] TRUE
xls_path  <- system.file("extdata", "datasets.xls", package = "readxl")
docx_path <- system.file("doc_examples", "landscape.docx", package = "officer")
csv_path  <- system.file("csv", "pt.csv", package = "sf")
wb <- wb_load(xslx_path)
wb_load(docx_path)
#> Error in wb_load(docx_path): File does not appear to be xlsx, xlsm or xlsb:  /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/officer/doc_examples/landscape.docx
wb_load(xls_path)
#> Error: Unable to open and load file:  /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/readxl/extdata/datasets.xls …
```

[misc] further file type and file extension checking

---

R/wb_load.R
tests/testthat/test-read_sources.R

Allows reading the file shared in https://github.com/tidyverse/readxl/issues/736 by @hidekoji. The xml scheme is somewhat inconsistent. For instance it is mixing all lower case letters and camel case: 
* in `[content_types.xml]` there is a reference to `sharedStrings.xml`, the same is in `/xl/_rels/workbook.xml.rels`
* in `xl/` there is `sharedstrings.xml`
* there is also a custom xml namespace `d3p1` available in `workbook.xml`
There might be other shenanigans with these type of files, after all this only contains two worksheets with data. It looks like some Japanese finance data, at least I can read IFRS? So far there is only this single file available, therefore not sure that I will merge this.
``` r
url <- "https://www.dropbox.com/scl/fi/jirejqyyxig0cikk6i2bn/P_P1.xl …
```

[load] read file with d3p1 namespace

---

NEWS.md
R/RcppExports.R
R/converters.R
R/read.R
R/wb_functions.R
R/wb_load.R
src/RcppExports.cpp
src/helper_functions.cpp
src/load_workbook.cpp
src/openxlsx2_types.h
src/write_file.cpp

TL;DR: This PR lifts the burden of calling `Rcpp::String()` for the `cc` columns `r`, `row_r` and `c_r`, which are filled for every cell of data frame (`A1`, `1` `A`). This should bring some speedups.
Back in the day we were troubled by non unicode systems which were unable to convert unicode characters into their locale. The solution is to pass strings through `Rcpp::String()` which makes sure that the correct locale is picked up. Unfortunately this is quite slow in comparison to `std::string()` (IIRC every string has to be created in R, contrary to `std::string()` which does not have to be passed to R). Using `Rcpp::String()` is not only slow, it also worsens with more data. Ultimately, if `Rcpp::String()` is called a lot, it will slow things down.
Sadly we will have to remain using …

[misc] cleanups and avoid some unneeded `Rcpp::String`

---

NEWS.md
R/class-workbook.R
R/xl_open.R
inst/AUTHORS
inst/WORDLIST
man/xl_open.Rd

It might be beneficial to reduce the calls to create_border, determining dims and style names when creating borders. Previously all borders, dims and styles where pre-created, kudos for readability, minus for performance :)
I would have loved to test with `devtools::test()`, but I might miss the "external standards" to test against?! 
``` 
Error in `get(genname, envir = envir)`: object 'compare_proxy' not found
```

Reworked borders

---

NEWS.md
R/RcppExports.R
R/class-workbook-wrappers.R
R/class-workbook.R
R/write_xlsx.R
inst/WORDLIST
inst/include/pugixml/pugiconfig.hpp
man/wbWorkbook.Rd
man/wb_save.Rd
src/RcppExports.cpp
src/write_file.cpp
tests/testthat/test-write.R

This is an experimental branch, using a custom C++ function to stream the XML file to disk. It is working, but not extensively tested and might still lack features. It has shown that it can reduce the memory consumption significantly.

[save] Stream Worksheet XML to Disk

---

NEWS.md
R/wb_load.R
tests/testthat/test-loading_workbook.R

``` r
wb <- openxlsx2::wb_load("https://foss.heptapod.net/-/project/322/uploads/01141236733f5f5173ded0f7dad5b59f/2_pis.xlsx")
wb$worksheets[[1]]$sheetFormatPr
#> [1] "<sheetFormatPr baseColWidth=\"8\" defaultRowHeight=\"16\" x14ac:dyDescent=\"0.2\"/>"
```

[load] apply fix when loading earlier created output files

---

src/strings_xml.cpp
tests/testthat/test-read_sources.R
tests/testthat/test-strings_xml.R

Previously they were treated as `NA_character_`. This caused issues with files imported from third party software. In these files, cells with blank `inlineStr` were treated as character, irritating our guess column type logic resulting in character columns instead of numeric columns

[read] treat blank inlineStr/sst as ""

---

R/helper-functions.R

This allows creating formula shapes (see #784):
``` r
xml_fml <- function(x) {
out <- vapply(x, FUN = function(y) {
sprintf(
'<a14:m>
<m:oMathPara xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math">
<m:oMathParaPr>
<m:jc m:val="centerGroup" />
</m:oMathParaPr>
%s
</m:oMathPara>
</a14:m>
<a:endParaRPr lang="en-GB" sz="1100" />',
read_xml(
equatags::transform_mathjax(y, to = "mml"),
pointer = FALSE)
)
}, FUN.VALUE = NA_character_)
vapply(out, read_xml, pointer = FALSE, NA_character_)
}
eqs <- c(
"x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}"
)
fml <- xml_fml(eqs)[1]
fml <- paste0(
openxlsx2:::fmt_txt2("Some formula: \n"),
fml
)
shp <- create_shape(text = fml, shape = "heart")
add_drawing(dims = "A1:D8", xml = shp)
if …
```

[shape] enable markup compability

---

NEWS.md
R/write.R
tests/testthat/test-formulas.R

fixes #1294
This does not apply to pivot table formulas only to plain cell formulas, arrays formulas, and cm formulas

[fml] normalize formulas and fix another cc bug

---

NEWS.md
R/class-workbook-wrappers.R
R/helper-functions.R
man/wb_add_data.Rd
man/wb_add_data_table.Rd
man/write_datatable.Rd
src/helper_functions.cpp
tests/testthat/test-write.R

We can assign labels to `NaN` using `labelled`. Since R factors are integers, any `NaN`, `Inf` or `-Inf` will be converted to `NA`. And both the underlying value and the label will be lost, because we want to create a label for `NaN` and the actual value is now `NA_character_`.
``` r
factor(c(1, NaN, 3), c("1", "NAN", "3"))
#> [1] 1    <NA> 3   
#> Levels: 1 NAN 3
```

[write] Inf, -Inf, and NaN

---

R/helper-functions.R
R/read.R
man/wb_to_df.Rd
tests/testthat/test-date_time_conversion.R
tests/testthat/test-named_regions.R

closes #1334
Various things can happen with date/datetime variables.
* date detection enabled and works
* conversion to date/datetime (either to a character, if `convert = FALSE` or to a Date/POSIXct column)
* mixed column not primarily dates: conversion to unixtime (probably the most confusing change)
*  date detection disabled
* date/datetime will show as spreadsheet date
``` r
packageVersion("openxlsx2")
#> [1] '1.14.0.9000'
wb <- wb_workbook()$add_worksheet()
wb$add_data(dims = "A1", x = "Var1")
wb$add_data(dims = "A2", x = "2024-01-01")
wb$add_data(dims = "A3", x = as.Date("2024-01-01"))
wb$to_df()
#>                Var1
#> 2        2024-01-01
#> 3 1704067200.000000
wb$to_df(convert = FALSE)
#>         Var1
#> 2 2024-01-01
#> 3 2024-01-01
wb$to_df(detect_dates = …
```

[read] Document changes to reading date/datetime

---

R/dates.R
R/read.R
R/write.R
tests/testthat/test-date_time_conversion.R

``` r
packageVersion("openxlsx2")
#> [1] '1.14.0.9000'
wb <- wb_workbook()$add_worksheet()
wb$add_data(dims = "A1", x = "Var1")
wb$add_data(dims = "B1", x = "Var2")
wb$add_data(dims = "C1", x = "Var3")
wb$add_data(dims = "A2", x = "2024-01-31")
wb$add_data(dims = "B2", x = "2024-01-31")
wb$add_data(dims = "C2", x = "2024-01-31")
wb$add_data(dims = "A3", x = as.Date("2024-02-01"))
wb$add_data(dims = "B3", x = structure(1234, units = "secs", class = c("hms", "difftime")))
wb$add_data(dims = "C3", x = as.POSIXct("2024-04-25 08:47:03", tz = "UTC"))
wb$to_df()
#>         Var1       Var2                Var3
#> 2 2024-01-31 2024-01-31          2024-01-31
#> 3 2024-02-01   00:20:34 2024-04-25 08:47:03
```

[read] reduce date/datetime differences to releases prior 1.15

---

R/class-color.R
R/helper-functions.R
inst/AUTHORS
man/wb_color.Rd
tests/testthat/test-helper-functions.R

This PR allows specifying colour format in the RGBA format and fixes #1340 
RGBA format is the default colour format in R, e.g., from `adjustcolor("black")`.
The default for spreadsheets and assumed by openxlsx2 even for the R interface is ARGB.
The ARGB format seems to be baked deeply within the codebase, so transition ARGB -> RGBA for a more natural R interface is likely out of question.
Thus, a simple `format` argument was added to `validate_color` and `wb_color` functions so that user can specify R-native format if they are passing RGBA value, without having to do the transformation themselves.

Add an option to specify colour in a RGBA format (default in R) -- Fix for #1340

---

NEWS.md
R/class-workbook-wrappers.R
R/class-workbook.R
R/conditional_formatting.R
man/wb_add_conditional_formatting.Rd
tests/testthat/test-conditional_formatting.R
tests/testthat/test-wb_styles.R

This is a working implementation of #1346, but it reveals a major breakage.
Previously, the following would draw a mesh over the entire dimension, even though the `dims` argument itself would indicate indicate that only columns A and K are required. I'm not sure that I want this and probably, this would require a warning, whenever two columns are selected.
```R
df <- mtcars
wb_dims(cols = c(1, ncol(df)), rows = seq_len(nrow(df)))
#> "A1:A32,K1:K32"
```
Also this probably would require some further testing, I only tested the case below:
```R
set.seed(123)
add_data(x = matrix(sample(c(0, 1), replace = TRUE, size = 100), ncol = 10, nrow = 10),
row_names = FALSE
)
wb$add_fill(dims = openxlsx2::wb_dims(rows = 1, cols = seq(from = 1, to = …
```

[cf] Allow multiple non-consequtive dims
