JanMarvin/openxlsx2

NEWS.md, R/class-workbook-utils.R, R/class-workbook.R, R/wb_load.R, R/write.R, tests/testthat/test-cloneWorksheet.R, tests/testthat/test-deleting_tables.R, tests/testthat/test-loading_workbook_tables.R
* avoid wrangling with list attributes
* avoid having references to deleted tables
=> replace tables list object with data frame

R/class-workbook.R, R/wb_load.R
This is a fix for the current slicer behaviour. And another call for a check when saving that all relationships are available.
=> [R/load&save] change slicer numbers. closes #203

R/RcppExports.R, R/class-workbook.R, R/class-worksheet.R, R/pugixml.R, src/RcppExports.cpp, src/pugi.cpp, src/write_file.cpp
Make use of XPtrXML when saving
=> Encoding xptrxml

.github/workflows/pkgdown.yaml
Reverts JanMarvin/openxlsx2#248
Should be fixed now in upstream packages
=> Revert "[manual] check for ggplot2"

NEWS.md, R/write.R, tests/testthat/test-writeData.R
=> 246 data warn

R/class-workbook.R, tests/testthat/test-class-workbook.R
fixes the second issue in #294
=> fix set_sheet_names

R/class-workbook.R, tests/testthat/test-remove_worksheets.R
=> fix remove_worksheet

R/class-workbook.R, R/wb_load.R, tests/testthat/test-read_sources.R
fix reading and writing charts with uneven styles, colors and rels
=> fix reading charts. fixes #318

R/wb_load.R, tests/testthat/test-loading_workbook.R
If no sheet is found, stop and return the sheets found in the workbook.
=> stop if sheet not found. closes 319

R/wb_functions.R, tests/testthat/test-read_from_created_wb.R, tests/testthat/test-wb_functions.R
if both are provided, they should be identical
=> align dims and rows & cols

R/class-workbook.R, vignettes/Update-from-openxlsx.Rmd
I'll review it tomorrow and will merge afterwards and update directly in main.
=> Begin a basic upgrade vignette

NEWS.md, R/write.R, tests/testthat/test-class-hyperlink.R
=> [wb_add_data] encode formula

R/write.R
Previously code was spread in two separate if clauses.
=> simplify code

R/class-style_mgr.R
=> fix partial match. closes #364

inst/include/pugixml/pugiconfig.hpp, inst/include/pugixml/pugixml.cpp, inst/include/pugixml/pugixml.hpp
=> [pugixml] update to release 1.13

vignettes/openxlsx2_basic_manual.Rmd
=> [vignettes] fix a replace all mistake

NEWS.md, R/readWorkbook.R, man/read_xlsx.Rd, man/wb_read.Rd
We might review these functions altogether. In the beginning I wanted to keep the results similar to what `openxlsx` returned, but today I do not see much sense in providing varying options for this wrapper.
=> add ... as argument for wb_to_df() wrappers

NEWS.md, R/class-chart-sheet.R, R/class-worksheet.R, tests/testthat/test-read_sources.R
=> Fix sheetPr creation. fixes #416

DESCRIPTION, NEWS.md, R/class-workbook.R, R/readWorkbook.R, R/wb_load.R, man/wbWorkbook.Rd, man/wb_read.Rd, tests/testthat/test-read_sources.R
handle custom properties and cleanup in `wb_load()`
=> Doc custom

NEWS.md, R/dates.R, R/write.R, tests/testthat/test-wb_functions.R
fixes the 1900-03-29 bug, simplify the code and fixes a possible round up bug in convert_date.
=> tweaks for dates.

R/helperFunctions.R
Either `openxlsx` or Libreoffice or both create worksheets with this headerFooter:
```XML
<headerFooter differentFirst="false" differentOddEven="false">
<oddHeader />
<oddFooter />
</headerFooter>
```
=> [wb_load] avoid bailing with empty header

NEWS.md, R/class-workbook.R, R/wb_load.R, tests/testthat/test-read_sources.R
=> [wb_load] support chartEX

R/class-workbook.R, man/wbWorkbook.Rd, tests/testthat/test-class-workbook-wrappers.R, tests/testthat/test-class-workbook.R
This was overlooked when reworking row attributes.
=> Fix setting and removing row heights

DESCRIPTION, NEWS.md, R/class-workbook.R, tests/testthat/test-class-workbook.R
begin new dev
fix add_drawing(). add test. update NEWS. remove commented code.
=> fix add_drawing() sheet logic. closes #457

NEWS.md, R/wb_functions.R, src/helper_functions.cpp, src/load_workbook.cpp, tests/testthat/test-strings_xml.R
This reverts the previous "fix"
=> Fix writing xml escaped characters. fixes #467

DESCRIPTION, NEWS.md, revdep/README.md
* 2022-12-18: First submission
=> release 0.4.1

NEWS.md, R/class-workbook.R
copy paste error mixing left and right
=> fix typo in add_border

NEWS.md, R/wb_load.R, tests/testthat/test-read_sources.R
We had some outdated logic in our slicer/slicerCache loading code
=> fix slicer and slicerCache loading. fixes #504

R/class-workbook.R, R/wb_load.R
Loads pivot xml files to workbook. Cleans up the pivot logic.
=> Load pivot

.github/workflows/check-standard.yaml, R/wb_load.R
Found a xlsx file at work that has `<Relationships xmlsx ... />` and no `Relationship` children. Presumably written by SAS Base 9 something. Currently we can not read this file.
=> Empty relship

R/write.R, src/helper_functions.cpp
=> safe speedups for add_data

.github/workflows/check-standard.yaml, DESCRIPTION, NEWS.md, README.Rmd, README.md, revdep/README.md
* 2023-01-29 First submission to CRAN
* 2023-01-29 Second submission to CRAN addressing a note on the r-universe badge and the default C++ standard
=> release 0.5

R/baseXML.R, R/class-workbook.R, tests/testthat/test-class-workbook.R
This ensures that drawings rId and chart num are correct. Fixes a regression that no longer allowed the assignment of multiple charts per worksheet.
=> additional cleanup from #536

NEWS.md, R/wb_functions.R, man/wb_to_df.Rd, tests/testthat/test-wb_functions.R
cleans up code and improves date detection (fixes #391)
=> Improve wb to df

DESCRIPTION, NEWS.md, inst/WORDLIST, revdep/README.md
* 2023-02-26 first submission
* 2023-02-26 second submission (fixed URLs)
=> release 0.5.1

DESCRIPTION, NEWS.md, R/write_xlsx.R
closes #552
- don't ignore NULL for na.strings
- bump dev version
- update news
=> 552 write null

NEWS.md, R/wb_functions.R, tests/testthat/test-read_from_created_wb.R
Though I had fixed it, but that was unsuccessful. 
Needs a test ...
=> Type date conv

NEWS.md, R/class-workbook-wrappers.R, R/class-workbook.R, R/class-worksheet.R, man/cleanup.Rd, man/wbWorkbook.Rd, man/wbWorksheet.Rd, tests/testthat/test-clean_sheet.R
```R
xlsx <- system.file("extdata", "oxlsx2_sheet.xlsx", package = "openxlsx2")
wb <- wb_load(xlsx)
wb <- wb_clean_sheet(wb = wb, sheet = 1, dims = "B3:F4", numbers = TRUE, characters = TRUE, styles = FALSE, merged_cells = TRUE)
wb$open()
```
=> add dims argument to wb_clean_sheet(). closes #562

vignettes/Update-from-openxlsx.Rmd
Hi @Moohan, does this fit or would you like more examples?
=> extend examples for chains and pipes. closes #561

R/class-color.R
=> avoid dot functions of R > 3.4.0. closes #568

NEWS.md, R/class-workbook-wrappers.R, R/class-workbook.R, R/utils.R, R/wb_functions.R, man/wbWorkbook.Rd, man/wb_add_chart_xml.Rd, man/wb_add_drawing.Rd, man/wb_add_image.Rd, man/wb_add_mschart.Rd, man/wb_add_plot.Rd, tests/testthat/test-class-workbook.R
Based on a suggestion by @rfineman this improves image/chart placement.
* `wb_add_image()` and `wb_add_plot()` gain a `dims` argument
* `wb_add_mschart()`, `wb_add_charts_xml()` and `wb_add_drawing()` gain `colOffset` and `rowOffset` arguments
=> [wb_add_image] add dims. closes #576 

tests/testthat/test-wb_functions.R
```R
> packageVersion("waldo")
[1] ‘0.4.0.9000’
> devtools::test()
ℹ Testing openxlsx2
Starting 2 test processes
✔ | F W S  OK | Context
✔ |        17 | asserts [0.3s]                                                                           
✔ |         2 | base_font                                                                                
✔ |     1   0 | class-chart-sheet                                                                        
─────────────────────────────────────────────────────────────────────────────────────────────────────────
Skip (test-class-chart-sheet.R:2:1): class wbChartSheet works
Reason: empty test
─────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ |         6 | class-color [0.7s] …
```
=> [test] improve test for waldo. closes #584

.Rbuildignore, DESCRIPTION, NEWS.md, R/expect-wrapper.R, inst/WORDLIST, revdep/README.md, src/load_workbook.cpp
* 2023-04-21: first submission to CRAN
=> Release 0.6.1

NEWS.md, R/RcppExports.R, R/class-workbook-wrappers.R, R/class-workbook.R, R/write.R, inst/WORDLIST, man/wbWorkbook.Rd, man/wb_add_formula.Rd, man/write_formula.Rd, src/RcppExports.cpp, src/helper_functions.cpp, src/openxlsx2_types.h, tests/testthat/test-formulas.R, vignettes/openxlsx2_formulas.Rmd, vignettes/openxlsx2_formulas_manual.Rmd
add arguments to use formulas with `cm` cell metadata and `ref` cell …reference
=> [wb_add_formula] updates to formulas including vignette. closes #490

NEWS.md, R/class-style_mgr.R, R/class-workbook.R, R/wb_styles.R, R/write.R, man/create_dxfs_style.Rd, man/style_mgr.Rd, man/wbWorkbook.Rd, tests/testthat/test-conditional_formatting.R, tests/testthat/test-styles_xml.R, tests/testthat/test-tables.R, tests/testthat/test-wb_styles.R
This allows slightly better dxf element tweaking.
```R
wb <- wb_workbook() %>%
wb_add_worksheet(gridLines = FALSE)
tabCol1 <- create_dxfs_style(bgFill = wb_color(theme = 7))
tabCol2 <- create_dxfs_style(bgFill = wb_color(theme = 5), patternType = "")
tabBrd1 <- create_dxfs_style(border = TRUE)
tabCol3 <- create_dxfs_style(bgFill = wb_color(hex = "FFC00000"), font_color = wb_color("white"))
wb$add_style(tabCol1)
wb$add_style(tabCol2)
wb$add_style(tabBrd1)
wb$add_style(tabCol3)
xml <-   sprintf(
"<tableStyle name=\"RedTableStyle\" pivot=\"0\" count=\"%s\" xr9:uid=\"{91A57EDA-14C5-4643-B7E3-C78161B6BBA4}\">
<tableStyleElement type=\"wholeTable\" dxfId=\"%s\"/>
<tableStyleElement type=\"headerRow\" dxfId=\"%s\"/>
<tableStyleElement type=\"firstRowStripe\" dxfId=\"%s\"/> …
```
=> load tableStyles

R/class-workbook.R, tests/testthat/test-class-workbook-wrappers.R, tests/testthat/test-read_xlsx_random_seed.R
create random strings for axis ids
=> Random axis ids

R/wb_load.R
forgot to assign this
Might wanna check the effect of the following:
```XML
<LinksUpToDate>false</LinksUpToDate>
<HyperlinksChanged>false</HyperlinksChanged>
```
=> [wb_load] assign loaded app.xml

R/wb_styles.R, tests/testthat/test-wb_styles.R
to allow
```R
wb$add_cell_style(wrapText = TRUE)
```
=> [wbStyles] Add as_xml_attr

NEWS.md, R/class-workbook-wrappers.R, R/class-workbook.R, man/wbWorkbook.Rd, man/wb_add_conditional_formatting.Rd, tests/testthat/test-conditional_formatting.R, vignettes/conditional-formatting.Rmd
for #643 
```R
wb <- wb_workbook()$add_worksheet()$add_data(x = mtcars)
wb$add_conditional_formatting(
dims = "B2:F5",
type = 'between',
rule = c(2, 4)
)
```
=> [cf] add dims argument

NEWS.md, R/read.R
show formulas was called to early in the function. dates would override formulas
=> return all formulas. previously dates would interfere

R/class-workbook-wrappers.R, R/class-workbook.R, R/read.R, R/wb_functions.R, R/wb_load.R, R/write.R, man/wbWorkbook.Rd, man/wb_sheet_names.Rd, tests/testthat/test-class-workbook.R
=> [get_sheet_names] add escape argument. closes #252

NEWS.md, vignettes/openxlsx2_formulas_manual.Rmd
Obviously nobody ever ran this code in the Redmond spread sheet software. Don't trust LibreOffice ... 😞
=> [vignette] Fix dataTable formula

R/utils.R, man/wb_add_formula.Rd, tests/testthat/test-utils.R
fixes https://github.com/pteridin/flexlsx/issues/2#issuecomment-1689861438
=> [fmt_txt] escape xml

DESCRIPTION, NEWS.md, README.Rmd, README.md, man/openxlsx2-package.Rd, revdep/README.md
Finally the one zero release is approaching.
* 2023-08-25 : first CRAN submission
=> Release 1.0

NEWS.md, R/class-workbook-utils.R, R/class-workbook-wrappers.R, R/class-workbook.R, man/grouping-wb.Rd
Previously it was required to create columns with `wb$createCols()`.
=> [wb_group_cols()] automate column creation

R/wb_load.R, src/xlsb.cpp, src/xlsb_defines.h, src/xlsb_funs.h, tests/testthat/helper.R, tests/testthat/test-read_xlsb.R
For each strange thing I find, there is a governmental example file 🙈
=> [xlsb] more fixes for formula heavy workbooks

R/class-workbook.R, tests/testthat/test-wb_styles.R
Should be straight forward, but needs testing, I don't want surprises.
=> [workbook] move default style initialization to workbook. fixes #803

R/class-workbook.R
=> [update_table] guard against unknown xml nodes

R/class-workbook.R, README.md, tests/testthat/test-class-workbook.R
``` r
add_worksheet("Sheet 1")$
add_worksheet("Sheet 1 (1)")$
add_worksheet("Sheet & NoSheet")
wb
#> A Workbook object.
#>  
#> Worksheets:
#>  Sheets: Sheet 1, Sheet 1 (1), Sheet & NoSheet 
#>  Write order: 1, 2, 3
```
=> [wbWorkbook] separate sheets in print() with comma. closes #46

R/class-workbook.R
but where our from worksheet has no media
=> [clone] fix cloning from a workbook with included media

DESCRIPTION, NEWS.md, R/class-workbook-wrappers.R, R/wb_styles.R, man/create_dxfs_style.Rd, man/wb_page_setup.Rd, revdep/README.md, revdep/cran.md
* 2023-10-23: First submission to CRAN
* 2023-10-23: Second submission to CRAN: Adressing R-Devel CMD check NOTEs
=> Release 1.1

R/write.R, tests/testthat/test-formulas.R
Realized that this is a more general move and covers a few more cases.
=> [write_data] make formula encoding more general

R/class-workbook.R, R/helper-functions.R, tests/testthat/test-cloneWorksheet.R
Haven't tested this with MS365 and it is the first pull request I was about to drop 80% in, because I probably will never have a use case for this. But this came up in #827
=> [clone] column and row styles

R/converters.R, R/illegal-characters.R, R/wb_styles.R, R/write.R, tests/testthat/test-class-workbook.R, tests/testthat/test-writing_posixct.R
* forward escaping of forward slash in numfmts
* code cleanup
* adding openxlsx2.maxWidth
=> [numfmt] fix forward slash escaping. closes #847

NEWS.md, R/class-workbook.R
solves ref issues with empty cells
=> [copy cells] fill empty cells

R/class-workbook.R, R/helper-functions.R
``` r
example_df <- data.frame(
type = c("EU", "US", "US", "EU", "EU", "EU"),
location = c("London", "NYC", "NYC", "Berlin", "Madrid", "London"),
amount = c(7, 5, 3, 2.5, 6, 1)
)
wb <- wb_workbook() %>% 
wb_add_worksheet() %>% 
wb_add_data(x = example_df)
df <- wb_data(wb)
wb <- wb %>%
wb_add_pivot_table(
df, dims = "A3", rows = "location", filter = "type", data = "location",
slicer = "location", pivot_table = "pt1",
param = list(
choose = c(type = 'x %in% c("EU")')
)
) %>% 
wb_add_slicer(
x = df, dims = "E2", 
slicer = "location", pivot_table = "pt1", 
param = list(
choose = c(
location = 'x %in% c("London", "Madrid")'
)
)
)
```
=> [pt] cleanup choose

src/xlsb.cpp, src/xlsb_funs.h
No clue how to reproduce CRANs issue, but this or disabling the lines altogether should solve their issue.
=> [xlsb] fix formats. closes #860

DESCRIPTION, NEWS.md, revdep/README.md
* 2023-11-29: First submission
=> Release 1.2

R/class-workbook-wrappers.R
=> Add reference to book

DESCRIPTION, NEWS.md, revdep/README.md
* 2024-01-12: First submission
=> Release 1.3

R/write.R
In a future version, this spaghetti code should be replaced by something more stable. The conversion to a data frame should be done as soon as possible, and this additional conversion should not be necessary at all.
=> [write] fix hyperlink issue with third party class tbl_df. closes #893

R/class-workbook-wrappers.R, R/write_xlsx.R, man/filter-wb.Rd, man/grouping-wb.Rd, man/wb_order.Rd, man/wb_page_setup.Rd, tests/testthat/test-helper-functions.R, tests/testthat/test-tables.R
=> Snake case conversion.

DESCRIPTION, NEWS.md, revdep/README.md
* 2024-02-16: First submission
=> Release 1.4

R/class-workbook-wrappers.R, man/col_widths-wb.Rd
=> Fix doc typo 

DESCRIPTION, R/class-workbook.R, R/wb_load.R, man/wbWorkbook.Rd, tests/testthat/test-read_sources.R
First part handling of `richData` folder #981
=> [load] read & write richData folder

DESCRIPTION, R/class-workbook.R, R/get-named-regions.R, R/helper-functions.R, R/write.R, tests/testthat/test-class-comment.R, tests/testthat/test-class-workbook-wrappers.R, tests/testthat/test-class-workbook.R, tests/testthat/test-styles_xml.R
Just so I don't send them in small pieces, I decided to do a scrubbing.
+ changed running order of tests, since read_sources and class-workbook-wrappers are the slowest tests
=> Partial match

R/pivot_table.R
I'm pretty sure there was a question on StackOverflow asking for how to do just this in `openxlsx2` at the beginning of the month, but it was closed, because the question was not reproducible and has since been removed.
=> [pt] provide downfill option. This fill labels vertically

DESCRIPTION, NEWS.md, man/convert_date.Rd
* 2024-05-01: first submission
=> Release 1.6

src/helper_functions.cpp, src/xlsb.cpp
"The value of this field MUST be less than or equal to 16."
=> [xlsb] fix max ccolspan

src/helper_functions.cpp, src/styles_xml.cpp, src/xlsb_funs.h
`-Wconversion -Wno-sign-conversion`
=> fix warnings from implicit conversions

R/wb_load.R, src/xlsb.cpp, src/xlsb_funs.h, tests/testthat/test-read_xlsb.R
This needs a utf8 substring function, because unfortunately nothing can be simple with unicode strings. Might need a little more testing, because strings could be lost if the string size calculation is wrong.
=> [xlsb] enable rich txt

_pkgdown.yml
Addresses a wish in https://github.com/JanMarvin/openxlsx2/pull/682#discussion_r1260262193
Now supported with [pkgdown 2.1](https://www.tidyverse.org/blog/2024/07/pkgdown-2-1-0/)
=> Add dark mode to website

src/xlsb_funs.h
=> [xlsb] comment due to gcc 12 false positive. Was not used.

R/wb_load.R, tests/testthat/test-wb_functions.R
If passing a file, this is handled with `data_only = TRUE` argument of `wb_load()`. closes #1121
=> [wb_to_df] Fix `skip_hidden_cols = TRUE`. closes #1121

R/read.R, man/wb_to_df.Rd
=> [doc] add a sentence how the column type is selected. closes #1117

NEWS.md, R/class-workbook.R, R/read.R, man/wbWorkbook.Rd, man/wb_to_df.Rd, tests/testthat/test-read_sources.R
=> [read] add `show_hyperlinks` argument. closes #1135

NEWS.md, R/read.R, man/wb_to_df.Rd, tests/testthat/test-write.R
to handle partial matches and accept character classes of the wanted type
=> [wb_to_df] improve types. closes #1146

DESCRIPTION, NEWS.md
* 2024-10-17: first submission
=> Release 1.10

R/RcppExports.R, R/converters.R, R/write.R, src/RcppExports.cpp, src/helper_functions.cpp, src/load_workbook.cpp, src/openxlsx2.h, tests/testthat/test-pugi_cpp.R
Various cleanups to the c++ code that writes R objects into workbooks.
This moves `Rcpp::checkUserInterupts()` to it's own function. Previously this was called every iteration, which probably was to much. The new function triggers a check every 10.000 cells. Basically what it does is allowing to stop Rcpp loops gently, so that if the Rcpp function is interrupted the function stops. Previously it would stop immediately, now the check if a stop event was called waits until 10.000 cells are passed. This should allow stopping for huge datasets, but it wont stop as instantaneous as the previous code would.
=> [misc] Cleanup cpp code

NEWS.md, R/class-workbook.R, R/write.R, tests/testthat/test-write.R
Previously it replaced the last row of the table, which *caused* loss of data.
=> [table] total row must be placed below the table. fixes #1178

DESCRIPTION, NEWS.md, inst/WORDLIST
=> Release 1.11

NEWS.md, R/class-workbook-wrappers.R, R/class-workbook.R, man/wbWorkbook.Rd, man/wb_set_bookview.Rd, tests/testthat/test-class-workbook-wrappers.R, tests/testthat/test-class-workbook.R
Previously I had considered using remove as part of wb_set_bookview(), but now this is no longer necessary.
=> [misc] unify arguments

src/helper_functions.cpp, src/load_workbook.cpp, src/openxlsx2.h, src/openxlsx2_types.h, src/pugi.cpp, src/styles_xml.cpp, src/xlsb.cpp, src/xlsb_funs.h
```diff
diff --git a/src/Makevars b/src/Makevars
index 3f68e15f..787ad5d6 100644
--- a/src/Makevars
+++ b/src/Makevars
@@ -1 +1,6 @@
-PKG_CPPFLAGS = -I. -I../inst/include/pugixml
+PKG_CPPFLAGS = -I. -isystem ../inst/include/pugixml \
+  -Wall \
+  -Wpedantic \
+  -Wshadow \
+  -Wunused \
+  -Wconversion
diff --git a/src/openxlsx2_types.h b/src/openxlsx2_types.h
index 84bca5dd..ec39ccdc 100644
--- a/src/openxlsx2_types.h
+++ b/src/openxlsx2_types.h
@@ -4,6 +4,13 @@
*                                                                            *
******************************************************************************/
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wall"
+#pragma clang diagnostic ignored "-Wpedantic"
+#pragma clang diagnostic ignored "-Wshadow" …
```
=> [misc] C++ cleanup

src/RcppExports.cpp, src/helper_functions.cpp, src/openxlsx2.h, src/pugi.cpp, src/strings_xml.cpp, src/styles_xml.cpp, src/write_file.cpp, src/xlsb.cpp, src/xlsb_funs.h
And for consistency move `int` and `unsigned int` to fixed width types
* `int` to `int32_t`
* `unsigned int` to `uint32_t`
=> [misc] Fix `-Wsign-compare`

R/class-workbook.R, R/wb_load.R, src/styles_xml.cpp, tests/testthat/test-read_sources.R, tests/testthat/test-styles_xml.R, tests/testthat/test-wb_styles.R
This is used for these checkboxes in MS365: https://techcommunity.microsoft.com/blog/excelblog/introducing-checkboxes-in-excel/4173561
=> [load] read featurePropertyBag folder

DESCRIPTION, NEWS.md
* 2024-12-19: first submission
=> Release 1.12

R/class-comment.R, R/class-workbook.R, R/class-worksheet.R, R/helper-functions.R, R/utils.R, R/write.R, man/dims_helper.Rd, tests/testthat/test-utils.R, tests/testthat/test-wb_functions.R
And use this in code. To be a bit more explicit of what is going on.
=> [misc] return a named list in dims_to_rowcol()

NEWS.md, R/class-workbook.R, tests/testthat/test-class-workbook.R
This extends the column width for integer columns to avoid some issues and the fixes very wide columns with doubles
=> [styles] improve column width "auto".

src/helper_functions.cpp, src/load_workbook.cpp, src/openxlsx2.h, src/openxlsx2_types.h, src/pugi.cpp, src/strings_xml.cpp, src/styles_xml.cpp, src/write_file.cpp, src/xlsb.cpp, src/xlsb_defines.h, src/xlsb_funs.h
Using this:
`clang-format -style="{BasedOnStyle: Chromium, ColumnLimit: 120}" -i *`
=> [Rcpp] cleanup format

R/utils.R, man/wb_dims.Rd
Hello, openxlsx2 is really useful. While learning it, I noticed that a right parenthesis was missing here, and I've already filled it in the PR.
=> Add the missing right parenthesis

R/class-workbook.R, src/write_file.cpp
cherry-pick commits from #1255
=> [save] No copy sheet data

.Rbuildignore, DESCRIPTION, NEWS.md
* 2025-02-15: first submission
=> Release 1.13

R/helper-functions.R, tests/testthat/test-loading_workbook.R
=> [load] Allow newlines in header footer

NEWS.md, R/utils.R, R/write.R, man/fmt_txt.Rd, tests/testthat/test-utils.R
related to https://github.com/pteridin/flexlsx/issues/40
=> [fmt_txt] protect against zero length strings

NEWS.md, R/class-worksheet.R
=> [style] set baseColWidth to 8.

NEWS.md, R/write.R
=> [write] make sure that `cc` and `x` have the same columns

R/wb_functions.R, tests/testthat/test-read_sources.R
pandas uses upper case numfmt for dates
=> [read] check against lower case numfmt

R/write.R, tests/testthat/test-formulas.R, tests/testthat/test-write.R
=> [write] fix named hyperlinks as documented

NEWS.md, R/class-workbook.R, R/write.R, tests/testthat/test-outlines.R
=> [grouping] initializes rows if required

NEWS.md, R/write_xlsx.R, tests/testthat/test-save.R
=> [write] support table name in write_xlsx()

NEWS.md, R/helper-functions.R
=> [write] improve code to avoid bottlenecks

R/wb_styles.R
=> [styles] set default value for create_fill()

NEWS.md, R/RcppExports.R, R/utils.R, R/wb_functions.R, man/create_numfmt.Rd, src/RcppExports.cpp, src/helper_functions.cpp, src/openxlsx2.h
=> [dims] improve `dims_to_dataframe()`

R/RcppExports.R, R/helper-functions.R, R/read.R, R/wb_load.R, src/RcppExports.cpp, src/helper_functions.cpp, src/openxlsx2.h, src/strings_xml.cpp, src/write_file.cpp, tests/testthat/test-strings_xml.R, tests/testthat/test-utils.R
=> [dims] allow dims to be all column or all row

R/class-style_mgr.R, R/class-workbook-wrappers.R, R/class-workbook.R, R/wb_styles.R, R/write.R, man/create_cell_style.Rd, vignettes/openxlsx2_style_manual.Rmd
Mostly internal parts of #1330
=> [misc] convert camelCase to snake_case

DESCRIPTION, NEWS.md, R/read.R, man/wb_to_df.Rd
* 2025-04-25: first submission
=> Release 1.15

R/wb_load.R
=> [load] silently remove missing relationships

R/class-workbook.R
=> [wb_set_grid_lines] Allow setting print = FALSE

R/class-workbook.R, R/wb_load.R, tests/testthat/test-loading_workbook.R
=> [load+save] initial implementation of namedSheetView

NEWS.md, R/class-style_mgr.R, R/class-workbook-wrappers.R, R/class-workbook.R, R/wb_styles.R, man/wbWorkbook.Rd, man/wb_add_border.Rd, man/wb_add_conditional_formatting.Rd, tests/testthat/test-styles_xml.R, tests/testthat/test-wb_styles.R
closes #1312
```R
add_border(dims = "A1:B10")$
add_border(dims = "C1:D10")
wb$add_border(dims = "A1:D1", overwrite = TRUE)
wb$add_border(dims = "A4:D4", top_border = NULL, overwrite = TRUE)
wb$add_worksheet()$
add_border(dims = "B2:D4", bottom_border = "thick", left_border = "thick", right_border = "thick", top_border = "thick")$
add_border(dims = "C3:E5", overwrite = TRUE)
wb$add_worksheet()$
add_border(dims = "B2:B4", bottom_border = "thick", left_border = "thick", right_border = "thick", top_border = "thick")$
add_border(dims = "B3:B3", 
top_border = NULL, left_border = NULL, right_border = NULL, bottom_border = "double",
top_color = NULL, left_color = NULL, right_color = NULL, bottom_color = wb_color("blue"),
overwrite = TRUE)$ …
```
=> [borders] add update option

NEWS.md, R/class-workbook-wrappers.R, R/helper-functions.R, R/read.R, man/wb_add_border.Rd, tests/testthat/test-formulas.R
=> [read] with dims and shared formulas incorrect results were returned

R/openxlsx2-package.R, R/read.R, man/openxlsx2-package.Rd, man/wb_to_df.Rd
=> [docs] add section regarding supported files

DESCRIPTION, NEWS.md, R/class-workbook.R, R/wb_load.R, tests/testthat/test-read_sources.R
The input file was created using the data set provided via this example: [Introducing value tokens in Microsoft Excel](https://techcommunity.microsoft.com/blog/microsoft365insiderblog/introducing-value-tokens-in-microsoft-excel/4398092)
=> [load+save] handle more richData files

NEWS.md, R/class-workbook-wrappers.R, R/class-workbook.R, R/wb_styles.R, man/wbWorkbook.Rd, man/wb_add_border.Rd, man/wb_add_fill.Rd, tests/testthat/test-wb_styles.R
``` r
add_fill(
dims = "B2:D4",
color = wb_color("white"),
bg_color = wb_color("black"),
pattern = "lightUp"
)$
add_border(
dims = "B6:D8",
diagonal_up = "thin",
diagonal_down = "thin",
diagonal_color = wb_color("red")
)
```
=> [styles] add background color and diagonal border argument to style functions

NEWS.md, R/utils.R, man/dims_helper.Rd, man/wb_dims.Rd, tests/testthat/test-utils.R
=> [dims] add type argument

R/utils.R, tests/testthat/test-utils.R
=> [dims] allow types to be a vector

NEWS.md, R/class-comment.R, R/class-workbook.R, R/class-worksheet.R, R/read.R, R/utils.R, R/write.R, src/helper_functions.cpp
* Improve dims_to_df()
* Avoid unname(unlist()) for unlist(use.names = FALSE)
* avoid multiple calls to dims_to_dataframe() (this can probably be improved)
=> [misc] speedup a few style functions

R/class-workbook.R, tests/testthat/test-class-worksheet.R
=> [print] remove print options instead of setting it to false

DESCRIPTION, R/dates.R, R/utils.R, man/convert_date.Rd
=> [misc] fix `convert_date()` arguments
